from collections import defaultdict
from enum import IntEnum

from django.apps import apps
from django.contrib.auth.models import Group, Permission
from django.core.management.base import BaseCommand


class UserGroup(IntEnum):
    SELAILIJA = 1
    VALMISTELIJA = 2
    SOPIMUSVALMISTELIJA = 3
    SYOTTAJA = 4
    PERINTALAKIMIES = 5
    LASKUTTAJA = 6
    PAAKAYTTAJA = 7


UG = UserGroup

DEFAULT_MODEL_PERMS = {
    # "areasource": {
    # },
    # "area": {
    # },
    "areanote": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "decisionmaker": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "decisiontype": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "decision": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "change"),
        UG.SOPIMUSVALMISTELIJA: ("view", "change"),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "change"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "conditiontype": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "condition": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "change"),
        UG.SOPIMUSVALMISTELIJA: ("view", "change"),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "change"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "creditdecision": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: (
            "view",
            "send_creditdecision_inquiry",
            "send_sanctions_inquiry",
        ),
        UG.SOPIMUSVALMISTELIJA: (
            "view",
            "send_creditdecision_inquiry",
            "send_sanctions_inquiry",
        ),
        UG.SYOTTAJA: (
            "view",
            "send_creditdecision_inquiry",
            "send_sanctions_inquiry",
        ),
        UG.PERINTALAKIMIES: (
            "view",
            "send_creditdecision_inquiry",
            "send_sanctions_inquiry",
        ),
        UG.LASKUTTAJA: (
            "view",
            "send_creditdecision_inquiry",
            "send_sanctions_inquiry",
        ),
        UG.PAAKAYTTAJA: (
            "view",
            "add",
            "change",
            "delete",
            "send_creditdecision_inquiry",
            "send_sanctions_inquiry",
        ),
    },
    "creditdecisionreason": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "creditdecisionlog": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "rentintendeduse": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "rent": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "change"),
        UG.SOPIMUSVALMISTELIJA: ("view", "change"),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "change"),
        UG.LASKUTTAJA: ("view", "change"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "rentduedate": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view", "add", "change", "delete"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "fixedinitialyearrent": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "contractrent": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "indexadjustedrent": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "equalizedrent": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view",),
    },
    "rentadjustment": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "managementsubvention": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "managementsubventionformofmanagement": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "temporarysubvention": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "payablerent": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "index": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "leasebasisofrent": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "leasebasisofrentmanagementsubvention": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "leasebasisofrenttemporarysubvention": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "basisofrentplottype": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "basisofrentbuildpermissiontype": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "basisofrent": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "basisofrentrate": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "basisofrentpropertyidentifier": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "basisofrentdecision": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "commenttopic": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "comment": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view", "add", "change", "delete"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "contact": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "change"),
        UG.LASKUTTAJA: ("view", "add", "change", "delete"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "contracttype": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "contract": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "change"),
        UG.SOPIMUSVALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "change"),
        UG.LASKUTTAJA: ("view", "change"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "collateral": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view", "add", "change", "delete"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "collateraltype": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "contractchange": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "change"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "collectionletter": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "collectionlettertemplate": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "collectionnote": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view", "add", "change", "delete"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "collectioncourtdecision": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "customdetailedplan": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "interestrate": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "leasetype": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "municipality": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "district": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "areasearchintendeduse": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "intendeduse": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "statisticaluse": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "supportivehousing": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "financing": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "management": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "regulation": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "hitas": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "noticeperiod": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "specialproject": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "reservationprocedure": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "leaseidentifier": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "lease": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view", "change"),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view", "change"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete", "delete_nonempty"),
    },
    "leasestatelog": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view",),
    },
    "relatedlease": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "infilldevelopmentcompensation": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "infilldevelopmentcompensationlease": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "infilldevelopmentcompensationdecision": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "infilldevelopmentcompensationintendeduse": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "infilldevelopmentcompensationattachment": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "inspection": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "inspectionattachment": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "receivabletype": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "invoiceset": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view", "add", "change", "delete"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "invoice": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view", "add", "change", "delete"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "invoicerow": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view", "add", "change", "delete"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "invoicenote": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view", "add", "change", "delete"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "invoicepayment": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view", "add", "change", "delete"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "leasearea": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "leaseholdtransfer": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view", "delete"),
        UG.SYOTTAJA: ("view", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "delete"),
    },
    "leaseholdtransferparty": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view", "delete"),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "delete"),
    },
    "leaseholdtransferproperty": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view", "delete"),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "delete"),
    },
    "leaseareaaddress": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "leaseareaattachment": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "constructabilitydescription": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "plot": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "plotsearch": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "plotsearchstage": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "plotsearchtype": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    # TODO These are copypasted from above
    "plotsearchsubtype": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "targetstatus": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "usagedistribution": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "areasearch": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "informationcheck": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "relatedplotapplication": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "planunittype": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "plotdivisionstate": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "planunitstate": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "planunitintendeduse": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "planunit": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "serviceunit": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view",),
    },
    "tenant": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view", "change"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "tenantcontact": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view", "add", "change"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "tenantrentshare": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view", "add", "change"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "vat": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "olddwellingsinhousingcompaniespriceindex": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "applicationmetadata": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "uidata": {
        UG.SELAILIJA: ("view", "add", "change", "delete"),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view", "add", "change", "delete"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete", "edit_global_ui_data"),
    },
    "user": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view",),
    },
    "landuseagreement": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "landuseagreementattachment": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "landuseagreementinvoice": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view", "add", "change", "delete"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "landuseagreementinvoicepayment": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view", "add", "change", "delete"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "landuseagreementinvoicerow": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view", "add", "change", "delete"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "landuseagreementinvoiceset": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view", "add", "change", "delete"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "landuseagreementlitigant": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view", "add", "change", "delete"),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "landuseagreementcondition": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "landuseagreementcompensation": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "landuseagreementdecision": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "landuseagreementdecisioncondition": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "landuseagreementreceivabletype": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    # Batchrun
    "command": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: None,
        UG.SOPIMUSVALMISTELIJA: None,
        UG.SYOTTAJA: None,
        UG.PERINTALAKIMIES: None,
        UG.LASKUTTAJA: None,
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "job": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "jobrun": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view",),
    },
    "jobrunlogentry": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view",),
    },
    "jobrunqueueitem": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: None,
        UG.SOPIMUSVALMISTELIJA: None,
        UG.SYOTTAJA: None,
        UG.PERINTALAKIMIES: None,
        UG.LASKUTTAJA: None,
        UG.PAAKAYTTAJA: ("view",),
    },
    "scheduledjob": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view",),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view",),
        UG.PERINTALAKIMIES: ("view",),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "timezone": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: None,
        UG.SOPIMUSVALMISTELIJA: None,
        UG.SYOTTAJA: None,
        UG.PERINTALAKIMIES: None,
        UG.LASKUTTAJA: None,
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    # TODO These are copypasted from plotsearch
    "form": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "answer": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "attachment": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    "areasearchattachment": {
        UG.SELAILIJA: ("view",),
        UG.VALMISTELIJA: ("view", "add"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add"),
        UG.PERINTALAKIMIES: ("view", "add"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add"),
    },
    "meetingmemo": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: ("view", "add", "change", "delete"),
        UG.SOPIMUSVALMISTELIJA: ("view",),
        UG.SYOTTAJA: ("view", "add", "change", "delete"),
        UG.PERINTALAKIMIES: ("view", "add", "change", "delete"),
        UG.LASKUTTAJA: ("view",),
        UG.PAAKAYTTAJA: ("view", "add", "change", "delete"),
    },
    # leasing.report_storage
    "reportstorage": {
        UG.SELAILIJA: None,
        UG.VALMISTELIJA: None,
        UG.SOPIMUSVALMISTELIJA: None,
        UG.SYOTTAJA: None,
        UG.PERINTALAKIMIES: None,
        UG.LASKUTTAJA: None,
        UG.PAAKAYTTAJA: ("view", "delete"),
    },
}

PERMISSION_TYPES = ("view", "add", "change", "delete")


class Command(BaseCommand):
    help = "Sets predefined model permissions for the predefined MVJ groups"

    def handle(self, *args, **options):  # NOQA
        groups = {group.id: group for group in Group.objects.all()}
        permissions = {perm.codename: perm for perm in Permission.objects.all()}

        all_model_permissions = []
        group_permissions = []
        app_names = [
            "credit_integration",
            "leasing",
            "users",
            "batchrun",
            "plotsearch",
            "forms",
        ]

        for app_name in app_names:
            for model in apps.get_app_config(app_name).get_models(
                include_auto_created=True
            ):
                model_name = model._meta.model_name

                if model_name not in DEFAULT_MODEL_PERMS:
                    self.stdout.write(
                        'Model "{}" not in DEFAULT_MODEL_PERMS. Skipping.'.format(
                            model_name
                        )
                    )
                    continue

                for permission_type in PERMISSION_TYPES:
                    all_model_permissions.append(
                        permissions["{}_{}".format(permission_type, model_name)]
                    )

                for custom_model_permission_name, desc in model._meta.permissions:
                    all_model_permissions.append(
                        permissions[custom_model_permission_name]
                    )

                for group_id, permission_types in DEFAULT_MODEL_PERMS[
                    model_name
                ].items():
                    if not permission_types:
                        continue

                    for permission_type in permission_types:
                        if permission_type in permissions:
                            permission = permissions[permission_type]
                        else:
                            permission = permissions[
                                "{}_{}".format(permission_type, model_name)
                            ]

                        group_permissions.append(
                            Group.permissions.through(
                                group=groups[group_id], permission=permission
                            )
                        )

        # Delete existing group permissions from the pre-defined groups
        mvj_groups = [grp for grp in groups.values() if grp.id in range(1, 8)]
        Group.permissions.through.objects.filter(
            group__in=mvj_groups, permission__in=all_model_permissions
        ).delete()

        # Save the desired field permissions for the groups
        Group.permissions.through.objects.bulk_create(group_permissions)

        # Logging
        permissions_by_group = defaultdict(list)
        for group_permission in group_permissions:
            permissions_by_group[group_permission.group.name].append(
                group_permission.permission.codename
            )
        for group_name, permissions in permissions_by_group.items():
            self.stdout.write(
                f'Added model permissions for group "{group_name}": {", ".join(permissions)}'
            )
