# Generated by Django 4.2.27 on 2026-01-20 14:19

from django.db import migrations

SCHEDULE_NAME = "push_auditlogs_to_elasticsearch"


def create_schedule(apps, schema_editor):
    """Create django_q schedule if it doesn't exist."""
    try:
        Schedule = apps.get_model("django_q", "Schedule")  # NOQA: N806
    except LookupError:
        # django_q is not installed, skip
        return

    Schedule.objects.update_or_create(
        name=SCHEDULE_NAME,
        defaults={
            "func": "audittrail.tasks.push_auditlogs_to_elasticsearch",
            "schedule_type": "I",  # I=Minutes
            "minutes": 15,
            "repeats": -1,  # Infinite repeats
        },
    )


def reverse_schedule(apps, schema_editor):
    """Remove the schedule on migration rollback."""
    try:
        Schedule = apps.get_model("django_q", "Schedule")  # NOQA: N806
    except LookupError:
        return

    Schedule.objects.filter(name=SCHEDULE_NAME).delete()


class Migration(migrations.Migration):
    """Adds a Django Q schedule to push audit logs to Elasticsearch."""

    initial = True

    dependencies = []

    operations = [
        migrations.RunPython(create_schedule, reverse_code=reverse_schedule),
    ]
