# Generated by Django 3.2.9 on 2021-12-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0061_make_service_unit_required"),
        ("users", "0003_alter_user_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="service_units",
            field=models.ManyToManyField(
                related_name="users", to="leasing.ServiceUnit"
            ),
        ),
    ]
