# Generated by Django 4.2.20 on 2025-05-30 07:42

from django.db import migrations
import django.contrib.auth.models


class Migration(migrations.Migration):
    # This migration was previously autogenerated by Django, and directly referenced
    # a Manager class from users.models.
    # The migration has been edited by removing the reference to the custom Manager from the migration,
    # so that it would not become an issue if that class is removed in the future.

    dependencies = [
        ("users", "0004_user_service_units"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
