# Generated by Django 4.2.20 on 2025-05-30 07:42

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_service_units"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.MvjUserManager()),
            ],
        ),
    ]
