# Generated by Django 4.2.17 on 2025-02-06 12:16

from django.db import migrations, models
import django.db.models.deletion
import file_operations.private_files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericAttachmentTestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_attachment",
                    file_operations.private_files.PrivateFileField(
                        storage=file_operations.private_files.PrivateFileSystemStorage(),
                        upload_to="",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GenericSafeDeleteAttachmentTestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "file_attachment",
                    file_operations.private_files.PrivateFileField(
                        storage=file_operations.private_files.PrivateFileSystemStorage(),
                        upload_to="",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FileScanStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "filefield_name",
                    models.CharField(
                        help_text="Name of the column of the content object's FileField"
                    ),
                ),
                (
                    "filepath",
                    models.CharField(
                        help_text="Filepath for preservation even after the original row has been deleted from a table referenced by the generic foreign key.",
                        max_length=255,
                        verbose_name="filepath",
                    ),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="scan time"
                    ),
                ),
                (
                    "file_deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deletion time"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="error message"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Scan Status",
                "verbose_name_plural": "File Scan Statuses",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="file_operat_content_a43c77_idx",
                    )
                ],
            },
        ),
    ]
