# Generated by Django 2.2.13 on 2021-09-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_answer_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
