# Generated by Django 2.2.24 on 2021-09-20 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0004_auto_20210915_1654"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="answer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="forms.Answer",
            ),
        ),
    ]
