# Generated by Django 2.2.24 on 2021-09-22 10:10

from django.db import migrations
import enumfields.fields
import forms.enums


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0005_entry_null_true"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="state",
            field=enumfields.fields.EnumField(
                default="work_in_progress", enum=forms.enums.FormState, max_length=30
            ),
        ),
    ]
