# Generated by Django 2.2.24 on 2021-10-15 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0006_form_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="add_new_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="add_new_text_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="add_new_text_fi",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="add_new_text_sv",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="field",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="forms.Section",
            ),
        ),
    ]
