# Generated by Django 3.2.9 on 2021-11-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0007_section_add_new_text_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="action",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="field",
            name="hint_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="field",
            name="hint_text_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="field",
            name="hint_text_fi",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="field",
            name="hint_text_sv",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="field",
            name="validation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
