# Generated by Django 3.2.9 on 2021-11-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0008_alter_field_model_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="action",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
