# Generated by Django 3.2.9 on 2021-11-10 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0009_alter_choice_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="forms.field",
            ),
        ),
    ]
