# Generated by Django 3.2.10 on 2022-02-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_alter_choice_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='extra_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
