# Generated by Django 3.2.12 on 2022-02-18 13:51

from django.db import migrations, models
import forms.models.form


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0012_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="attachment",
            field=models.FileField(
                upload_to=forms.models.form.get_attachment_file_upload_to
            ),
        ),
    ]
