# Generated by Django 3.2.12 on 2022-03-28 12:03

from django.db import migrations
import enumfields.fields
import forms.enums


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0014_add_create_and_open_fields_to_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="type",
            field=enumfields.fields.EnumField(
                default="show_always", enum=forms.enums.SectionType, max_length=30
            ),
        ),
    ]
