# Generated by Django 3.2.12 on 2022-04-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0015_section_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="path",
            field=models.TextField(default="error"),
            preserve_default=False,
        ),
    ]
