# Generated by Django 3.2.13 on 2022-09-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0017_add_entrysection_model_add_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="show_duplication_check",
            field=models.BooleanField(default=True),
        ),
    ]
