# Generated by Django 3.2.13 on 2022-09-21 12:44

from django.db import migrations
import enumfields.fields
import forms.enums


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0018_section_show_duplication_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="applicant_type",
            field=enumfields.fields.EnumField(
                default="both", enum=forms.enums.ApplicantType, max_length=30
            ),
        ),
    ]
