# Generated by Django 3.2.13 on 2023-02-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0019_section_applicant_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="is_area_form",
            field=models.BooleanField(default=False),
        ),
    ]
