# Generated by Django 3.2.13 on 2023-04-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0020_form_is_area_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="hint_text",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="field",
            name="hint_text_en",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="field",
            name="hint_text_fi",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="field",
            name="hint_text_sv",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="field",
            name="default_value",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
