# Generated by Django 3.2.13 on 2023-11-20 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forms", "0021_alter_hint_text_max_length_add_field_default_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="opened_at",
        ),
        migrations.CreateModel(
            name="AnswerOpeningRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_stamp", models.DateTimeField(auto_now=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "answer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_record",
                        to="forms.answer",
                    ),
                ),
                (
                    "openers",
                    models.ManyToManyField(
                        related_name="_forms_answeropeningrecord_openers_+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
