# Generated by Django 3.2.13 on 2023-11-09 12:42
from pathlib import Path

from django.db import migrations


class RunSQLFromFile(migrations.RunSQL):
    def __init__(self, sql_file, reverse_sql_file=None, **kwargs):
        super().__init__(sql="", **kwargs)
        self.sql_file = sql_file
        self.reverse_sql_file = reverse_sql_file
        self._sql = "unread"
        self._reverse_sql = "unread"

    @property
    def sql(self):
        if self._sql == "unread":
            self._sql = self._read_file(self.sql_file)
        return self._sql

    @sql.setter
    def sql(self, value):
        pass

    @property
    def reverse_sql(self):
        if self._reverse_sql == "unread":
            self._reverse_sql = self._read_file(self.reverse_sql_file)
        return self._reverse_sql

    @reverse_sql.setter
    def reverse_sql(self, value):
        pass

    def _read_file(self, filename):
        if filename is None:
            return None
        with open(Path(__file__).parent / filename, encoding="utf8") as fp:
            return fp.read()


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0022_create_answeropeningrecord_and_remove_opened_at_from_answer"),
        ("plotsearch", "0030_auto_20231031_1149"),
    ]

    operations = [
        RunSQLFromFile(
            sql_file="0023_create_form_view.sql",
            reverse_sql_file="0023_reverse_create_form_view.sql",
        ),
    ]
