# Generated by Django 4.2.14 on 2024-11-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0025_alter_answeropeningrecord_openers"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
