# Generated by Django 4.2.16 on 2025-01-14 07:42

import django.core.files.storage
from django.db import migrations
import forms.models.form
import file_operations.private_files


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0026_alter_answer_user_alter_attachment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="attachment",
            field=file_operations.private_files.PrivateFileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/attachments/", location="attachments"
                ),
                upload_to=forms.models.form.get_attachment_file_upload_to,
            ),
        ),
    ]
