# Generated by Django 5.2.15 on 2026-09-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0027_private_filefield"),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE forms_field SET type = 'hidden' WHERE type = 'fixme_hidden';",
            reverse_sql="UPDATE forms_field SET type = 'fixme_hidden' WHERE type = 'hidden';",
        ),
        migrations.AlterField(
            model_name="field",
            name="type",
            field=models.CharField(
                choices=[
                    ("textbox", "Tekstikenttä"),
                    ("textarea", "Tekstialue"),
                    ("dropdown", "Alasvetovalikko"),
                    ("checkbox", "Valintaruutu"),
                    ("radiobutton", "Radiopainike"),
                    ("radiobuttoninline", "Radiopainike linjassa"),
                    ("uploadfiles", "Lataa tiedosto"),
                    ("fractional", "Murtoluku"),
                    ("hidden", "Piilotettu"),
                ],
                max_length=255,
            ),
        ),
    ]
