# Generated by Django 2.2.6 on 2019-10-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("laske_export", "0001_initial"), ("leasing", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="laskepaymentslog",
            name="payments",
            field=models.ManyToManyField(to="leasing.InvoicePayment"),
        ),
        migrations.AddField(
            model_name="laskeexportlog",
            name="invoices",
            field=models.ManyToManyField(to="leasing.Invoice"),
        ),
    ]
