# Generated by Django 2.1.3 on 2018-12-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0037_make_lease_basis_of_rent_archivable'),
        ('laske_export', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaskePaymentsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('started_at', models.DateTimeField(verbose_name='Time started')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Time ended')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Finished?')),
                ('payments', models.ManyToManyField(to='leasing.InvoicePayment')),
            ],
            options={
                'verbose_name': 'Laske payments log',
                'verbose_name_plural': 'Laske payments logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
