# Generated by Django 2.2.12 on 2020-06-22 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0007_add_business_id_validator"),
        ("laske_export", "0002_auto_20191004_0950"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="LaskeExportLogInvoiceItem",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "invoice",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="leasing.Invoice",
                            ),
                        ),
                    ],
                    options={"db_table": "laske_export_laskeexportlog_invoices", },
                ),
                migrations.AlterField(
                    model_name="laskeexportlog",
                    name="invoices",
                    field=models.ManyToManyField(
                        through="laske_export.LaskeExportLogInvoiceItem",
                        to="leasing.Invoice",
                    ),
                ),
                migrations.AddField(
                    model_name="laskeexportloginvoiceitem",
                    name="laskeexportlog",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laske_export.LaskeExportLog",
                    ),
                ),
            ]
        )
    ]
