# Generated by Django 2.2.12 on 2020-06-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laske_export", "0003_extend_laske_export_log_invoices"),
    ]

    operations = [
        migrations.AlterModelTable(name="laskeexportloginvoiceitem", table=None,),
    ]
