# Generated by Django 2.2.12 on 2020-06-29 09:33

import enumfields.fields
from django.db import migrations, models

import laske_export.enums


class Migration(migrations.Migration):

    dependencies = [
        ("laske_export", "0004_rename_laske_export_log_invoices"),
    ]

    operations = [
        migrations.AddField(
            model_name="laskeexportloginvoiceitem",
            name="information",
            field=models.TextField(blank=True, verbose_name="information"),
        ),
        migrations.AddField(
            model_name="laskeexportloginvoiceitem",
            name="status",
            field=enumfields.fields.EnumField(
                blank=True,
                enum=laske_export.enums.LaskeExportLogInvoiceStatus,
                max_length=255,
                null=True,
                verbose_name="status",
            ),
        ),
        migrations.RunSQL(
            sql=[
                (
                    "UPDATE laske_export_laskeexportloginvoiceitem SET status = %s;",
                    ["sent"],
                )
            ],
            reverse_sql="UPDATE laske_export_laskeexportloginvoiceitem SET status = null;",
        ),
    ]
