# Generated by Django 2.2.13 on 2020-08-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0011_landuseagreementinvoice"),
        ("laske_export", "0005_add_fields_to_laske_export_log_invoice_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="laskeexportlog",
            name="land_use_agreement_invoices",
            field=models.ManyToManyField(to="leasing.LandUseAgreementInvoice"),
        ),
    ]
