# Generated by Django 3.2.18 on 2023-11-01 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0065_serviceunit_laske_fill_priority_and_info"),
        ("laske_export", "0006_laskeexportlog_land_use_agreement_invoices"),
    ]

    operations = [
        migrations.AddField(
            model_name="laskeexportlog",
            name="filename",
            field=models.CharField(
                max_length=255, blank=True, null=True, verbose_name="Filename"
            ),
        ),
        # Fill the filename field for all the existing logs that had invoices in them.
        # We can use hard coded Laske sender_id in the filename because until now the
        # value has always been "ID340".
        migrations.RunSQL(
            sql="""
            UPDATE laske_export_laskeexportlog
               SET filename = CONCAT('MTIL_IN_ID340_', LPAD(id::text, 8, '0'), '.xml')
             WHERE laske_export_laskeexportlog.id IN (
                       SELECT el.id
                         FROM laske_export_laskeexportlog el
                         LEFT JOIN laske_export_laskeexportloginvoiceitem ii
                           ON el.id = ii.laskeexportlog_id
                        GROUP BY el.id
                       HAVING COUNT(ii.id) > 0
                   )
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            UPDATE laske_export_laskeexportlog
               SET filename = ''
             WHERE laske_export_laskeexportlog.id IN (
                       SELECT el.id
                         FROM laske_export_laskeexportlog el
                         LEFT JOIN laske_export_laskeexportloginvoiceitem ii
                           ON el.id = ii.laskeexportlog_id
                        GROUP BY el.id
                       HAVING COUNT(ii.id) = 0
                   )
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="laskeexportlog",
            name="filename",
            field=models.CharField(max_length=255, blank=True, verbose_name="Filename"),
        ),
        migrations.AddField(
            model_name="laskeexportlog",
            name="service_unit",
            field=models.ForeignKey(
                # Add Service unit 1 (Maaomaisuuden kehittäminen ja tontit) for all the
                # existing rows
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.serviceunit",
                verbose_name="Service unit",
            ),
            preserve_default=False,
        ),
    ]
