# Generated by Django 4.2.27 on 2026-01-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laske_export", "0008_laskeexportlog_filename_and_service_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laskeexportlog",
            name="land_use_agreement_invoices",
        ),
    ]
