sudo: false
language: python
services:
  - postgresql

cache: pip

env:
  global:
    - SECRET_KEY=xxx
    - DATABASE_URL=postgis://postgres:@localhost/mvj

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -U pip
  - pip install -r requirements.txt -r requirements-dev.txt

before_script:
  - psql -U postgres -c 'create database mvj;'
  - psql -U postgres -c "create extension postgis;"

script:
  - flake8
  - py.test -ra -vvv --cov=mvj --cov=leasing
  - isort -c
