sudo: false
language: python
services:
  - postgresql

cache: pip

env:
  global:
    - SECRET_KEY=xxx
    - DATABASE_URL=postgis://postgres:@localhost/mvj
    - LEGACY_USER=''
    - LEGACY_PASSWORD=''
    - LEGACY_HOST=''
    - LEGACY_PORT=''
    - LEGACY_SERVICES=''

python:
  - "3.5"
  - "3.6"
  - "3.7"

addons:
  postgresql: '9.4'
  apt:
    packages:
      postgresql-9.4-postgis-2.3

install:
  - pip install -U pip
  - pip install codecov -r requirements.txt -r requirements-dev.txt

before_script:
  - psql -U postgres -c 'create database mvj;'
  - psql -U postgres -c "create extension if not exists postgis;"

script:
  - flake8
  - pytest -ra -vvv --cov=.
  - isort -c

after_success: codecov
