version: '3.7'
services:
    postgres:
        build: ./docker/postgres/
        environment:
            POSTGRES_USER: mvj
            POSTGRES_PASSWORD: mvj
            POSTGRES_DB: mvj
        expose:
            - "5432"
        volumes:
            - mvj-postgres-data-volume:/var/lib/postgresql/data
        container_name: mvj-db
        # networks:
        #     - net

    django:
        build:
            context: ./
            dockerfile: ./docker/django/Dockerfile
        command: python manage.py runserver 0:8001
        env_file:
            - docker-compose.env
        volumes:
            - .:/code
            - mvj-django-media-volume:/var/media/
        ports:
            - "8001:8001"
            - "5678:5678"
        depends_on:
            - postgres
        container_name: mvj
        restart: unless-stopped
        # networks:
        #     - net

volumes:
        mvj-postgres-data-volume:
        mvj-django-media-volume:
networks:
    default:
        external:
            name: tunnistamo_net
    net:
        driver: bridge

