version: '3.7'
services:
    postgres:
        build: ./docker/postgres/
        environment:
            POSTGRES_USER: mvj
            POSTGRES_PASSWORD: mvj
            POSTGRES_DB: mvj
        expose:
            - "5432"
        volumes:
            - mvj-postgres-data-volume:/var/lib/postgresql/data
        container_name: mvj-db

    django:
        build:
            context: ./
            dockerfile: ./docker/django/Dockerfile
        command: python manage.py runserver_plus 0:8000
        env_file:
            - docker-compose.env.yaml
        volumes:
            - .:/code
            - mvj-django-media-volume:/var/media/
        ports:
            - "8000:8000"
            - "5678:5678"
        depends_on:
            - postgres
        container_name: mvj
        restart: unless-stopped

volumes:
        mvj-postgres-data-volume:
        mvj-django-media-volume:
networks:
    default:
        name: helsinki

