# Generated by Django 5.2.15 on 2026-09-25 12:54

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgreementParty",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "party_type",
                    models.CharField(
                        blank=True,
                        choices=[("COMPANY", "Yritys"), ("PERSON", "Henkilö")],
                        max_length=255,
                    ),
                ),
                (
                    "ownership_share_numerator",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "ownership_share_denominator",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("name", models.CharField(blank=True)),
                ("national_identification_number", models.CharField(blank=True)),
                ("business_id", models.CharField(blank=True)),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fi", "Finnish"),
                            ("sv", "Swedish"),
                            ("en", "English"),
                        ],
                        max_length=10,
                    ),
                ),
                ("street_address", models.CharField(blank=True)),
                ("postal_code", models.CharField(blank=True)),
                ("city", models.CharField(blank=True)),
                (
                    "country",
                    django_countries.fields.CountryField(blank=True, max_length=2),
                ),
                ("care_of", models.CharField(blank=True)),
                ("phone", models.CharField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("note", models.TextField(blank=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LAND_OWNER", "Maanomistaja"),
                            ("DEVELOPER", "Toteuttaja"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AuthorizedSignatory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("name", models.CharField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signing_date", models.DateField(blank=True, null=True)),
                ("signing_deadline", models.DateField(blank=True, null=True)),
                ("first_invitation_sent_date", models.DateField(blank=True, null=True)),
                (
                    "second_invitation_sent_date",
                    models.DateField(blank=True, null=True),
                ),
                ("third_invitation_sent_date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("title", models.CharField(blank=True)),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LAND_USE_AGREEMENT", "Maankäyttösopimus"),
                            (
                                "REAL_ESTATE_PRELIMINARY_AGREEMENT",
                                "Kiinteistökaupan esitietosopimus",
                            ),
                            ("OTHER", "Muu"),
                        ],
                    ),
                ),
                ("contract_number", models.CharField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("title", models.CharField(blank=True)),
                (
                    "decision_maker",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LAND_MANAGER", "Tonttipäällikkö"),
                            (
                                "URBAN_ENVIRONMENT_COMMITTEE",
                                "Kaupunkiympäristölautakunta",
                            ),
                            ("CITY_BOARD", "Kaupunginhallitus"),
                        ],
                    ),
                ),
                ("decision_date", models.DateField(blank=True, null=True)),
                ("section", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "decision_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "EASEMENT_CONDITION_ADDITION",
                                "Rasite- ja/tai rasitteenluont.ehdon lis. (1 ehto)",
                            ),
                            (
                                "LAND_USE_AGREEMENT_APPROVAL",
                                "Maankäyttösopimuksen hyväksyntä",
                            ),
                        ],
                    ),
                ),
                ("diary_number", models.CharField(blank=True)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DetailedPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("plan_number", models.CharField(unique=True)),
                (
                    "processing_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "Vireillä"),
                            ("EFFECTIVE", "Lainvoimainen"),
                            ("REVOKED", "Kumottu"),
                        ],
                        max_length=255,
                    ),
                ),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("approver", models.CharField(blank=True)),
                ("diary_number", models.CharField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("name", models.CharField()),
                ("identifier", models.CharField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LandPolicyProgram",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("name", models.CharField(blank=True)),
                (
                    "default_discount_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteIntendedUse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("name", models.CharField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteTenureType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("name", models.CharField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BillingDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("ovt_code", models.CharField(blank=True)),
                ("sap_customer_number", models.CharField(blank=True)),
                ("customer_reference", models.CharField(blank=True)),
                (
                    "agreement_party",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_details",
                        to="landuse.agreementparty",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("name", models.CharField(blank=True)),
                ("phone", models.CharField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "agreement_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_persons",
                        to="landuse.agreementparty",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CashDepositCollateral",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guarantee_type",
                    models.CharField(
                        choices=[
                            ("MORTGAGE_DEED", "Panttikirja"),
                            ("CASH_DEPOSIT", "Rahavakuus"),
                            ("PERSONAL_GUARANTEE", "Omavelkainen takaus"),
                            ("DEPOSIT_PLEDGE", "Tilivarojen panttaus"),
                            ("OTHER", "Muu vakuus"),
                        ]
                    ),
                ),
                ("third_party_pledger_name", models.CharField(blank=True, null=True)),
                (
                    "third_party_pledger_business_id",
                    models.CharField(blank=True, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("returned_date", models.DateField(blank=True, null=True)),
                ("additional_information", models.TextField(blank=True)),
                ("guarantor_name", models.CharField(blank=True)),
                ("guarantor_business_id", models.CharField(blank=True)),
                (
                    "guarantor_national_identification_number",
                    models.CharField(blank=True),
                ),
                ("account_number", models.CharField(blank=True)),
                ("paid_at_date", models.DateField(blank=True, null=True)),
                (
                    "parties",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_collaterals",
                        to="landuse.agreementparty",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_collaterals",
                        to="landuse.contract",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContractChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signing_date", models.DateField(blank=True, null=True)),
                ("signing_deadline", models.DateField(blank=True, null=True)),
                ("first_invitation_sent_date", models.DateField(blank=True, null=True)),
                (
                    "second_invitation_sent_date",
                    models.DateField(blank=True, null=True),
                ),
                ("third_invitation_sent_date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="landuse.contract",
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_contract_schedule_details",
                        to="landuse.decision",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="decision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_contract_schedule_details",
                to="landuse.decision",
            ),
        ),
        migrations.CreateModel(
            name="DecisionCondition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "condition_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "EASEMENT_OR_EASEMENT_LIKE_CONDITION",
                                "Rasite ja/tai rasitteenluonteinen ehto",
                            ),
                            ("OTHER", "Muu ehto"),
                        ],
                    ),
                ),
                ("supervision_date", models.DateField(blank=True, null=True)),
                ("supervised_date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="landuse.decision",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DepositPledgeCollateral",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guarantee_type",
                    models.CharField(
                        choices=[
                            ("MORTGAGE_DEED", "Panttikirja"),
                            ("CASH_DEPOSIT", "Rahavakuus"),
                            ("PERSONAL_GUARANTEE", "Omavelkainen takaus"),
                            ("DEPOSIT_PLEDGE", "Tilivarojen panttaus"),
                            ("OTHER", "Muu vakuus"),
                        ]
                    ),
                ),
                ("third_party_pledger_name", models.CharField(blank=True, null=True)),
                (
                    "third_party_pledger_business_id",
                    models.CharField(blank=True, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("returned_date", models.DateField(blank=True, null=True)),
                ("additional_information", models.TextField(blank=True)),
                (
                    "document_category",
                    models.CharField(
                        blank=True,
                        choices=[("ELECTRONIC", "Sähköinen"), ("PAPER", "Paperinen")],
                    ),
                ),
                ("guarantor_name", models.CharField(blank=True)),
                ("guarantor_business_id", models.CharField(blank=True)),
                (
                    "guarantor_national_identification_number",
                    models.CharField(blank=True),
                ),
                ("account_number", models.CharField(blank=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_collaterals",
                        to="landuse.contract",
                    ),
                ),
                (
                    "parties",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_collaterals",
                        to="landuse.agreementparty",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("installment_sequence_number", models.PositiveSmallIntegerField()),
                ("installment_count_total", models.PositiveSmallIntegerField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("invoice_identifier", models.CharField(blank=True, unique=True)),
                (
                    "invoice_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LAND_USE_COMPENSATION", "Maankäyttökorvaus"),
                            ("PENALTY", "Sakko"),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Luonnos"),
                            ("OPEN", "Avoin"),
                            ("PAID", "Maksettu"),
                            ("CREDITED", "Hyvitetty"),
                        ],
                        default="DRAFT",
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "billed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("sap_xml", models.TextField(blank=True, null=True)),
                (
                    "recipient_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="landuse.agreementparty",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("LAND_USE_COMPENSATION", "Maankäyttökorvaus"),
                            ("INCREASE", "Korotus"),
                            ("INTEREST", "Korko"),
                            ("PENALTY", "Sakko"),
                        ]
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="landuse.invoice",
                    ),
                ),
            ],
            options={
                "ordering": (
                    models.Case(
                        models.When(
                            item_type="LAND_USE_COMPENSATION", then=models.Value(0)
                        ),
                        default=models.Value(1),
                        output_field=models.IntegerField(),
                    ),
                    "pk",
                ),
            },
        ),
        migrations.CreateModel(
            name="InvoiceRecipient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "party_type",
                    models.CharField(
                        blank=True,
                        choices=[("COMPANY", "Yritys"), ("PERSON", "Henkilö")],
                        max_length=255,
                    ),
                ),
                (
                    "ownership_share_numerator",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "ownership_share_denominator",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("name", models.CharField(blank=True)),
                ("national_identification_number", models.CharField(blank=True)),
                ("business_id", models.CharField(blank=True)),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fi", "Finnish"),
                            ("sv", "Swedish"),
                            ("en", "English"),
                        ],
                        max_length=10,
                    ),
                ),
                ("street_address", models.CharField(blank=True)),
                ("postal_code", models.CharField(blank=True)),
                ("city", models.CharField(blank=True)),
                (
                    "country",
                    django_countries.fields.CountryField(blank=True, max_length=2),
                ),
                ("care_of", models.CharField(blank=True)),
                ("phone", models.CharField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("note", models.TextField(blank=True)),
                (
                    "agreement_party",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="landuse.agreementparty",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceRecipientSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "party_type",
                    models.CharField(
                        blank=True,
                        choices=[("COMPANY", "Yritys"), ("PERSON", "Henkilö")],
                        max_length=255,
                    ),
                ),
                (
                    "ownership_share_numerator",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "ownership_share_denominator",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("name", models.CharField(blank=True)),
                ("national_identification_number", models.CharField(blank=True)),
                ("business_id", models.CharField(blank=True)),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fi", "Finnish"),
                            ("sv", "Swedish"),
                            ("en", "English"),
                        ],
                        max_length=10,
                    ),
                ),
                ("street_address", models.CharField(blank=True)),
                ("postal_code", models.CharField(blank=True)),
                ("city", models.CharField(blank=True)),
                (
                    "country",
                    django_countries.fields.CountryField(blank=True, max_length=2),
                ),
                ("care_of", models.CharField(blank=True)),
                ("phone", models.CharField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("note", models.TextField(blank=True)),
                ("ovt_code", models.CharField(blank=True)),
                ("sap_customer_number", models.CharField(blank=True)),
                ("customer_reference", models.CharField(blank=True)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient_snapshot",
                        to="landuse.invoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LandUseAgreement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("identifier", models.CharField(unique=True)),
                ("agreement_type", models.CharField(blank=True)),
                ("is_promotion_area", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "Luonnos"),
                            ("IN_PROGRESS", "Vireillä"),
                            ("NEGOTIATION", "Neuvottelu"),
                            ("DECISION", "Päätös"),
                            ("SIGNATURE", "Allekirjoitus"),
                            ("NO_AGREEMENT", "Ei sopimusta"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "estimated_presentation_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "estimated_payment_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("includes_housing_obligations", models.BooleanField(default=False)),
                ("obligations_deadline", models.DateField(blank=True, null=True)),
                (
                    "collateral_multiplier",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "authorized_signatory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="land_use_agreements",
                        to="landuse.authorizedsignatory",
                    ),
                ),
                (
                    "detailed_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="land_use_agreements",
                        to="landuse.detailedplan",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="land_use_agreements",
                        to="landuse.district",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="agreement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="landuse.landuseagreement",
            ),
        ),
        migrations.CreateModel(
            name="DetailedPlanSite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("identifier", models.CharField(blank=True)),
                (
                    "agreements",
                    models.ManyToManyField(
                        related_name="detailed_plan_sites",
                        to="landuse.landuseagreement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="decision",
            name="agreement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisions",
                to="landuse.landuseagreement",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="agreement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="landuse.landuseagreement",
            ),
        ),
        migrations.CreateModel(
            name="AgreementPreparer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "preparer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreement_preparers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preparers",
                        to="landuse.landuseagreement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="agreementparty",
            name="agreement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parties",
                to="landuse.landuseagreement",
            ),
        ),
        migrations.CreateModel(
            name="AgreementAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("street_address", models.CharField()),
                ("postal_code", models.CharField()),
                ("city", models.CharField()),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="landuse.landuseagreement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LandUseCompensation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("excel_calculation_url", models.URLField(blank=True, null=True)),
                (
                    "monetary_compensation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "land_compensation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "other_compensation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "total_compensation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("land_compensation_description", models.TextField(blank=True)),
                ("other_compensation_description", models.TextField(blank=True)),
                (
                    "value_before_detailed_plan_proposal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "demolition_or_other_deduction",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "land_use_compensation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "land_policy_program_discount_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "public_areas_m2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "public_areas_acquisition_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "agreement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensation",
                        to="landuse.landuseagreement",
                    ),
                ),
                (
                    "land_policy_program",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compensations",
                        to="landuse.landpolicyprogram",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MortgageDeedCollateral",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guarantee_type",
                    models.CharField(
                        choices=[
                            ("MORTGAGE_DEED", "Panttikirja"),
                            ("CASH_DEPOSIT", "Rahavakuus"),
                            ("PERSONAL_GUARANTEE", "Omavelkainen takaus"),
                            ("DEPOSIT_PLEDGE", "Tilivarojen panttaus"),
                            ("OTHER", "Muu vakuus"),
                        ]
                    ),
                ),
                ("third_party_pledger_name", models.CharField(blank=True, null=True)),
                (
                    "third_party_pledger_business_id",
                    models.CharField(blank=True, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("returned_date", models.DateField(blank=True, null=True)),
                ("additional_information", models.TextField(blank=True)),
                (
                    "document_category",
                    models.CharField(
                        blank=True,
                        choices=[("ELECTRONIC", "Sähköinen"), ("PAPER", "Paperinen")],
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        choices=[("PROPERTY", "Kiinteistö"), ("FACILITY", "Laitos")],
                    ),
                ),
                ("facility_identifier", models.CharField(blank=True)),
                ("mortgage_deed_number", models.CharField(blank=True)),
                ("mortgage_deed_date", models.DateField(blank=True, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_collaterals",
                        to="landuse.contract",
                    ),
                ),
                (
                    "parties",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_collaterals",
                        to="landuse.agreementparty",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MortgageDeedPropertyIdentifier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("identifier", models.CharField(blank=True)),
                (
                    "collateral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_identifiers",
                        to="landuse.mortgagedeedcollateral",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OtherCollateral",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guarantee_type",
                    models.CharField(
                        choices=[
                            ("MORTGAGE_DEED", "Panttikirja"),
                            ("CASH_DEPOSIT", "Rahavakuus"),
                            ("PERSONAL_GUARANTEE", "Omavelkainen takaus"),
                            ("DEPOSIT_PLEDGE", "Tilivarojen panttaus"),
                            ("OTHER", "Muu vakuus"),
                        ]
                    ),
                ),
                ("third_party_pledger_name", models.CharField(blank=True, null=True)),
                (
                    "third_party_pledger_business_id",
                    models.CharField(blank=True, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("returned_date", models.DateField(blank=True, null=True)),
                ("additional_information", models.TextField(blank=True)),
                (
                    "document_category",
                    models.CharField(
                        blank=True,
                        choices=[("ELECTRONIC", "Sähköinen"), ("PAPER", "Paperinen")],
                    ),
                ),
                ("guarantor_name", models.CharField(blank=True)),
                ("guarantor_business_id", models.CharField(blank=True)),
                (
                    "guarantor_national_identification_number",
                    models.CharField(blank=True),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_collaterals",
                        to="landuse.contract",
                    ),
                ),
                (
                    "parties",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_collaterals",
                        to="landuse.agreementparty",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Luonnos"),
                            ("PENDING_APPROVAL", "Odottaa hyväksyntää"),
                            ("APPROVED", "Hyväksytty"),
                            ("REJECTED", "Hylätty"),
                        ],
                        default="DRAFT",
                    ),
                ),
                ("rejected_reason", models.TextField(blank=True)),
                ("signing_date", models.DateField(blank=True, null=True)),
                (
                    "increase_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "base_interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "interest_margin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_schedules",
                        to="landuse.landuseagreement",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_schedules",
                        to="landuse.contract",
                    ),
                ),
                (
                    "recipient_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_schedules",
                        to="landuse.agreementparty",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentScheduleInstallment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("installment_sequence_number", models.PositiveSmallIntegerField()),
                ("installment_count_total", models.PositiveSmallIntegerField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "interest_calculation_period_start_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "interest_calculation_period_end_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "payment_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="landuse.paymentschedule",
                    ),
                ),
            ],
            options={
                "ordering": ("installment_sequence_number",),
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="source_payment_schedule_installment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice",
                to="landuse.paymentscheduleinstallment",
            ),
        ),
        migrations.CreateModel(
            name="PaymentScheduleInstallmentItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("LAND_USE_COMPENSATION", "Maankäyttökorvaus"),
                            ("INCREASE", "Korotus"),
                            ("INTEREST", "Korko"),
                        ]
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "installment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="landuse.paymentscheduleinstallment",
                    ),
                ),
            ],
            options={
                "ordering": (
                    models.Case(
                        models.When(
                            item_type="LAND_USE_COMPENSATION", then=models.Value(0)
                        ),
                        default=models.Value(1),
                        output_field=models.IntegerField(),
                    ),
                    "pk",
                ),
            },
        ),
        migrations.CreateModel(
            name="PersonalGuaranteeCollateral",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guarantee_type",
                    models.CharField(
                        choices=[
                            ("MORTGAGE_DEED", "Panttikirja"),
                            ("CASH_DEPOSIT", "Rahavakuus"),
                            ("PERSONAL_GUARANTEE", "Omavelkainen takaus"),
                            ("DEPOSIT_PLEDGE", "Tilivarojen panttaus"),
                            ("OTHER", "Muu vakuus"),
                        ]
                    ),
                ),
                ("third_party_pledger_name", models.CharField(blank=True, null=True)),
                (
                    "third_party_pledger_business_id",
                    models.CharField(blank=True, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("returned_date", models.DateField(blank=True, null=True)),
                ("additional_information", models.TextField(blank=True)),
                (
                    "document_category",
                    models.CharField(
                        blank=True,
                        choices=[("ELECTRONIC", "Sähköinen"), ("PAPER", "Paperinen")],
                    ),
                ),
                ("guarantor_name", models.CharField(blank=True)),
                ("guarantor_business_id", models.CharField(blank=True)),
                (
                    "guarantor_national_identification_number",
                    models.CharField(blank=True),
                ),
                ("guarantee_identifier", models.CharField(blank=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_collaterals",
                        to="landuse.contract",
                    ),
                ),
                (
                    "parties",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_collaterals",
                        to="landuse.agreementparty",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShadowSalesLedgerEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("paid_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("paid_date", models.DateField()),
                ("filing_code", models.CharField(blank=True, max_length=35)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="landuse.invoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgreementSite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("identifier", models.CharField(blank=True)),
                (
                    "area_m2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "floor_area_kem2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "preservation_designation",
                    models.CharField(
                        blank=True,
                        choices=[("SR1", "SR1"), ("SR2", "SR2"), ("SR3", "SR3")],
                        null=True,
                    ),
                ),
                ("has_housing_obligation", models.BooleanField(default=False)),
                (
                    "unit_price_euro_per_kem2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensation_sites",
                        to="landuse.landuseagreement",
                    ),
                ),
                (
                    "intended_use",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreement_sites",
                        to="landuse.siteintendeduse",
                    ),
                ),
                (
                    "tenure_types",
                    models.ManyToManyField(
                        related_name="agreement_sites", to="landuse.sitetenuretype"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="paymentscheduleinstallment",
            constraint=models.UniqueConstraint(
                fields=("payment_schedule", "installment_sequence_number"),
                name="unique_payment_schedule_installment_number",
            ),
        ),
    ]
