# Generated by Django 5.2.17 on 2026-10-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landuse", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agreementparty",
            name="ownership_share_denominator",
        ),
        migrations.RemoveField(
            model_name="agreementparty",
            name="ownership_share_numerator",
        ),
        migrations.RemoveField(
            model_name="invoicerecipient",
            name="ownership_share_denominator",
        ),
        migrations.RemoveField(
            model_name="invoicerecipient",
            name="ownership_share_numerator",
        ),
        migrations.RemoveField(
            model_name="invoicerecipientsnapshot",
            name="ownership_share_denominator",
        ),
        migrations.RemoveField(
            model_name="invoicerecipientsnapshot",
            name="ownership_share_numerator",
        ),
    ]
