# Generated by Django 5.2.15 on 2026-09-30 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landuse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landusecompensation",
            name="land_policy_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compensations",
                to="landuse.landpolicyprogram",
            ),
        ),
    ]
