# Generated by Django 5.2.17 on 2026-10-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landuse", "0002_remove_agreementparty_ownership_share_denominator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mortgagedeedcollateral",
            name="subsequent_pledgee_business_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mortgagedeedcollateral",
            name="subsequent_pledgee_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mortgagedeedcollateral",
            name="facility_identifier",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mortgagedeedcollateral",
            name="mortgage_deed_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="mortgagedeedcollateral",
            name="mortgage_deed_number",
            field=models.CharField(),
        ),
    ]
