# Generated by Django 5.2.17 on 2026-10-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "landuse",
            "0003_mortgagedeedcollateral_subsequent_pledgee_business_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cashdepositcollateral",
            name="marked_returned_by",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="depositpledgecollateral",
            name="marked_returned_by",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mortgagedeedcollateral",
            name="marked_returned_by",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="othercollateral",
            name="marked_returned_by",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalguaranteecollateral",
            name="marked_returned_by",
            field=models.CharField(blank=True, null=True),
        ),
    ]
