# Generated by Django 5.2.17 on 2026-10-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landuse", "0004_cashdepositcollateral_marked_returned_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="contract_number",
            new_name="identifier",
        ),
        migrations.AddField(
            model_name="contractchange",
            name="identifier",
            field=models.CharField(blank=True),
        ),
    ]
