# Generated by Django 5.2.17 on 2026-10-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landuse", "0005_rename_contract_number_contract_identifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="executor",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractchange",
            name="executor",
            field=models.CharField(blank=True, null=True),
        ),
    ]
