# Generated by Django 5.2.17 on 2026-10-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landuse", "0007_alter_landusecompensation_land_policy_program"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="district",
            options={"ordering": ("name",)},
        ),
    ]
