# Generated by Django 2.2.13 on 2020-12-16 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batchrun", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrun",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="jobrunlogentry",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="jobrunlogentry",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_entries",
                to="batchrun.JobRun",
                verbose_name="run",
            ),
        ),
    ]
