# Generated by Django 2.2.13 on 2021-01-22 07:55

from django.db import migrations, models
from enumfields.fields import EnumIntegerField

from ..enums import LogEntryKind


def fill_kind2_int_of_stderr_entries(apps, schema_editor):
    """
    Fill the new kind2 field of stderr entries.

    The stdout entries are not touched, since that is the default value
    for the kind2 field and therefore already correct.
    """
    log_entry_model = apps.get_model("batchrun", "JobRunLogEntry")
    log_entries = log_entry_model.objects.all()
    log_entries.filter(kind="stderr").update(kind2=LogEntryKind.STDERR)


def fill_kind_text_of_stderr_entries(apps, schema_editor):
    """
    Fill the old textual kind field of stderr entries.

    The stdout entries are not touched, since that is the default value
    for the old kind field (at the point of running this, see (*) below)
    and therefore already correct.
    """
    log_entry_model = apps.get_model("batchrun", "JobRunLogEntry")
    log_entries = log_entry_model.objects.all()
    log_entries.filter(kind2=LogEntryKind.STDERR).update(kind="stderr")


class Migration(migrations.Migration):
    dependencies = [
        ("batchrun", "0002_add_safedelete_to_logs"),
    ]

    operations = [
        migrations.AlterField(  # (*) Add default value to "kind" field
            model_name="jobrunlogentry",
            name="kind",
            field=models.CharField(max_length=30, default="stdout"),
        ),
        migrations.AddField(
            model_name="jobrunlogentry",
            name="kind2",
            field=EnumIntegerField(
                enum=LogEntryKind, default=LogEntryKind.STDOUT, verbose_name="kind"
            ),
        ),
        migrations.RunPython(
            code=fill_kind2_int_of_stderr_entries,
            reverse_code=fill_kind_text_of_stderr_entries,
        ),
        migrations.AlterField(
            model_name="jobrunlogentry",
            name="kind2",
            field=EnumIntegerField(enum=LogEntryKind, verbose_name="kind"),
        ),
        migrations.RemoveField(model_name="jobrunlogentry", name="kind"),
        migrations.RenameField("jobrunlogentry", "kind2", new_name="kind"),
    ]
