# Generated by Django 3.2.9 on 2021-11-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batchrun", "0011_log_compact_function"),
    ]

    operations = [
        migrations.AlterField(
            model_name="command",
            name="parameters",
            field=models.JSONField(blank=True, default=dict, verbose_name="parameters"),
        ),
        migrations.AlterField(
            model_name="job",
            name="arguments",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Argument for the command as a JSON object. These will be formatted with the parameter format string of the command. E.g. to pass value 123 as an argument to the rent_id parameter, set this to {"rent_id": 123}.',
                verbose_name="arguments",
            ),
        ),
    ]
