# Generated by Django 5.2.15 on 2026-09-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batchrun", "0013_auto_20240320_1524"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Time created"),
        ),
        migrations.AlterField(
            model_name="job",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Time modified"),
        ),
        migrations.AlterField(
            model_name="scheduledjob",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Time created"),
        ),
        migrations.AlterField(
            model_name="scheduledjob",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Time modified"),
        ),
    ]
