# Generated by Django 2.0.4 on 2018-04-24 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_subject_to_vat',
            field=models.BooleanField(default=False, verbose_name='Is subject to VAT?'),
        ),
        migrations.AddField(
            model_name='lease',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='lease',
            name='preparer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Preparer'),
        ),
        migrations.AddField(
            model_name='lease',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference number'),
        ),
        migrations.AddField(
            model_name='leasetype',
            name='sap_material_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SAP material code'),
        ),
        migrations.AddField(
            model_name='leasetype',
            name='sap_order_item_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SAP order item number'),
        ),
    ]
