# Generated by Django 2.0.3 on 2018-03-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_lessor',
            field=models.BooleanField(default=False, verbose_name='Is a lessor'),
        ),
    ]
