# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('Application', 'contact_person', 'contact_name'),
        migrations.AlterField(
            model_name='application',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact name'),
        ),
    ]
