# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0002_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID in the legacy system'),
        ),
    ]
