# Generated by Django 2.0.4 on 2018-04-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0002_add_fields_to_lease_and_lease_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['type', 'name', 'last_name', 'first_name']},
        ),
    ]
