# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leasing', '0002_rename_application_contact_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Address')),
                ('billing_address', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Billing address')),
                ('electronic_billing_details', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Electronic billing details')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone number')),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization name')),
                ('organization_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization address')),
                ('organization_is_company', models.BooleanField(default=False, verbose_name='Is organization a company')),
                ('organization_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization id')),
                ('organization_revenue', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization revenue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('name', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Name')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('article', models.CharField(blank=True, max_length=255, null=True, verbose_name='Article')),
                ('type', enumfields.fields.EnumField(enum=leasing.enums.DecisionType, max_length=255, verbose_name='Type')),
                ('type_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type description')),
                ('decision_maker', models.CharField(blank=True, max_length=255, null=True, verbose_name='Decision-maker')),
                ('link', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Link')),
                ('abstract', models.CharField(blank=True, max_length=4096, null=True, verbose_name='Abstract')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('note', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Note')),
                ('period_start_date', models.DateField(blank=True, null=True, verbose_name='Period start date')),
                ('period_end_date', models.DateField(blank=True, null=True, verbose_name='Period end date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Unit price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('is_reservation', models.BooleanField(default=False, verbose_name='Is a reservation?')),
                ('state', enumfields.fields.EnumField(enum=leasing.enums.LeaseState, max_length=255, verbose_name='State')),
                ('lease_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lease id')),
                ('reasons', models.TextField(blank=True, null=True, verbose_name='Reasons')),
                ('detailed_plan', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Detailed plan number')),
                ('detailed_plan_area', models.IntegerField(blank=True, null=True, verbose_name='Detailed plan area in full square meters')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaseAdditionalField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Field name')),
                ('value', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Field Value')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('requires_review', models.BooleanField(default=False, verbose_name='Requires review?')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Time reviewed')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_fields', to='leasing.Lease')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaseBuildingFootprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Use')),
                ('area', models.IntegerField(blank=True, null=True, verbose_name='Area in full square meters')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_footprints', to='leasing.Lease')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaseCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', enumfields.fields.EnumField(enum=leasing.enums.LeaseConditionType, max_length=255, verbose_name='Condition type')),
                ('description', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Description')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='leasing.Lease')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseRealPropertyUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Real property unit identification number')),
                ('name', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Name')),
                ('area', models.IntegerField(blank=True, null=True, verbose_name='Area in full square meters')),
                ('registry_date', models.DateField(blank=True, null=True, verbose_name='Registry date')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_property_units', to='leasing.Lease')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseRealPropertyUnitAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Address')),
                ('lease_property_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='leasing.LeaseRealPropertyUnit')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('rent_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rent id')),
                ('use', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Use')),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='Quantity / Area')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Unit price')),
                ('rent_percent', models.IntegerField(blank=True, null=True, verbose_name='Rent percent')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Discount')),
                ('discount_start_date', models.DateField(blank=True, null=True, verbose_name='Discount start date')),
                ('discount_end_date', models.DateField(blank=True, null=True, verbose_name='Discount end date')),
                ('increase', models.IntegerField(blank=True, null=True, verbose_name='Increase')),
                ('increase_start_date', models.DateField(blank=True, null=True, verbose_name='Increase start date')),
                ('increase_end_date', models.DateField(blank=True, null=True, verbose_name='Increase end date')),
                ('index', models.CharField(blank=True, max_length=255, null=True, verbose_name='Index')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='leasing.Lease')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('share', models.DecimalField(decimal_places=6, max_digits=7, verbose_name='Share of the rent')),
                ('billing_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_billing_contacts', to='leasing.Contact')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='leasing.Contact')),
                ('contact_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_contacts', to='leasing.Contact')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='leasing.Lease')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='BuildingFootprint',
            new_name='ApplicationBuildingFootprint',
        ),
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Time modified'),
        ),
        migrations.AddField(
            model_name='application',
            name='state',
            field=enumfields.fields.EnumField(default='unhandled', enum=leasing.enums.ApplicationState, max_length=255, verbose_name='Application state'),
        ),
        migrations.AddField(
            model_name='lease',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leasing.Application'),
        ),
        migrations.AddField(
            model_name='lease',
            name='preparer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='leasing.Tenant'),
        ),
        migrations.AddField(
            model_name='decision',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='leasing.Lease'),
        ),
    ]
