# Generated by Django 2.0.3 on 2018-03-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0002_contact_is_lessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasearea',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_areas', to='leasing.Lease'),
        ),
    ]
