# Generated by Django 2.0.4 on 2018-04-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0003_add_ordering_to_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivabletype',
            name='sap_code',
        ),
        migrations.AddField(
            model_name='receivabletype',
            name='sap_material_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SAP material code'),
        ),
        migrations.AddField(
            model_name='receivabletype',
            name='sap_order_item_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SAP order item number'),
        ),
    ]
