# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 10:06
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import leasing.models.lease


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0003_asset_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='status',
            field=enumfields.fields.EnumField(default='V', enum=leasing.models.lease.LeaseStatus, max_length=1, verbose_name='State'),
            preserve_default=False,
        ),
    ]
