# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0003_auto_20170502_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_billing_enabled',
            field=models.BooleanField(default=False, verbose_name='Is billing enabled?'),
        ),
        migrations.AddField(
            model_name='rent',
            name='type',
            field=enumfields.fields.EnumField(default='index', enum=leasing.enums.RentType, max_length=255, verbose_name='Rent type'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount'),
        ),
    ]
