# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import enumfields.fields
import leasing.models.client


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0004_lease_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID in the legacy system')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('postal_code', models.CharField(blank=True, max_length=255, verbose_name='Postal code')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='Country')),
                ('language', enumfields.fields.EnumIntegerField(enum=leasing.models.client.ClientLanguage, null=True, verbose_name='Language')),
                ('business_id', models.CharField(blank=True, max_length=9, verbose_name='Business ID')),
                ('fax_number', models.CharField(blank=True, max_length=255, verbose_name='Fax number')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Comment')),
                ('client_type', enumfields.fields.EnumIntegerField(enum=leasing.models.client.ClientType, null=True, verbose_name='Client type')),
                ('debt_collection', models.TextField(blank=True, verbose_name='Debt collection')),
                ('partnership_code', models.CharField(blank=True, max_length=4, verbose_name='Partnership code')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email')),
                ('trade_register', models.CharField(blank=True, max_length=7, verbose_name='Trade register')),
                ('ssid', models.CharField(blank=True, max_length=11, verbose_name='SSID')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Phone number')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='phone_numbers',
            field=models.ManyToManyField(blank=True, to='leasing.PhoneNumber', verbose_name='Phone numbers'),
        ),
    ]
