# Generated by Django 2.2.6 on 2020-03-11 13:09

from django.db import migrations
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0004_change_area_unit_as_required_to_leasebasisofrent")
    ]

    operations = [
        migrations.AlterField(
            model_name="leasebasisofrent",
            name="zone",
            field=enumfields.fields.EnumField(
                blank=True,
                enum=leasing.enums.BasisOfRentZone,
                max_length=20,
                null=True,
                verbose_name="Zone",
            ),
        ),
        migrations.RunSQL(
            """
            UPDATE leasing_leasebasisofrent set zone='zone_1' where zone='1';
            UPDATE leasing_leasebasisofrent set zone='zone_2' where zone='2';
            UPDATE leasing_leasebasisofrent set zone='zone_3' where zone='3';
        """,
            reverse_sql="""
            UPDATE leasing_leasebasisofrent set zone='1' where zone='zone_1';
            UPDATE leasing_leasebasisofrent set zone='2' where zone='zone_2';
            UPDATE leasing_leasebasisofrent set zone='3' where zone='zone_3';
        """,
        ),
    ]
