# Generated by Django 2.0.2 on 2018-02-19 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0004_lease_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('postal_code', models.CharField(max_length=255, verbose_name='Postal code')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('is_billpayer', models.BooleanField(default=False, verbose_name='Is billpayer')),
                ('is_contact', models.BooleanField(default=False, verbose_name='Is contact')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('language', models.CharField(max_length=255, verbose_name='Language')),
                ('ssid', models.CharField(max_length=255, verbose_name='SSID')),
                ('is_protected', models.BooleanField(verbose_name='Is protected')),
                ('customer_id', models.CharField(max_length=255, verbose_name='Customer ID')),
                ('sap_customer_number', models.CharField(max_length=255, verbose_name='SAP customer number')),
                ('comment', models.CharField(max_length=255, verbose_name='Comment')),
                ('shares_numerator', models.PositiveIntegerField(verbose_name='Numerator')),
                ('shares_denominator', models.PositiveIntegerField(verbose_name='Denominator')),
                ('ovt_identifier', models.CharField(max_length=255, verbose_name='OVT identifier')),
                ('partner_code', models.CharField(max_length=255, verbose_name='Partner code')),
                ('reference', models.CharField(max_length=255, verbose_name='Reference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('postal_code', models.CharField(max_length=255, verbose_name='Postal code')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('is_billpayer', models.BooleanField(default=False, verbose_name='Is billpayer')),
                ('is_contact', models.BooleanField(default=False, verbose_name='Is contact')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('language', models.CharField(max_length=255, verbose_name='Language')),
                ('ssid', models.CharField(max_length=255, verbose_name='SSID')),
                ('is_protected', models.BooleanField(verbose_name='Is protected')),
                ('customer_id', models.CharField(max_length=255, verbose_name='Customer ID')),
                ('sap_customer_number', models.CharField(max_length=255, verbose_name='SAP customer number')),
                ('comment', models.CharField(max_length=255, verbose_name='Comment')),
                ('main_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasing.MainTenant', verbose_name='Main tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
