# Generated by Django 2.0.2 on 2018-02-16 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0004_lease_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('identifier', models.CharField(max_length=255, verbose_name='Identifier')),
                ('area', models.PositiveIntegerField(blank=True, null=True, verbose_name='Area')),
                ('cross_section', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cross section')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('postal_code', models.CharField(max_length=255, verbose_name='Postal code')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('land_subdivision_id', models.CharField(max_length=255, verbose_name='Land subdivision ID')),
                ('land_subdivision_confirmation_date', models.DateField(verbose_name='Land subdivision confirmation date')),
                ('city_plan_id', models.CharField(max_length=255, verbose_name='City plan ID')),
                ('city_plan_confirmation_date', models.DateField(verbose_name='City plan confirmation date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanPlotState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanPlotType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanPlotUsagePurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='planplot',
            name='plan_plot_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.PlanPlotState', verbose_name='Plan plot state'),
        ),
        migrations.AddField(
            model_name='planplot',
            name='plan_plot_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.PlanPlotType', verbose_name='Plan plot type'),
        ),
        migrations.AddField(
            model_name='planplot',
            name='usage_purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.PlanPlotUsagePurpose', verbose_name='Usage purpose'),
        ),
    ]
