# Generated by Django 2.2.12 on 2020-06-02 09:03

from django.db import migrations
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0005_change_zone_as_enumfield_in_leasebasisofrent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="type",
            field=enumfields.fields.EnumField(
                enum=leasing.enums.AreaType, max_length=31, verbose_name="Area type"
            ),
        ),
    ]
