# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0005_auto_20170508_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='discount_end_date',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='discount_start_date',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='increase',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='increase_end_date',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='increase_start_date',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='index',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='rent_id',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='rent_percent',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_billing_contacts', to='leasing.Contact'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reference_number',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Reference number'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='state',
            field=enumfields.fields.EnumField(default='pending', enum=leasing.enums.InvoiceState, max_length=255, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='lease',
            name='bills_per_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bills per year'),
        ),
        migrations.AddField(
            model_name='lease',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='lease',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AddField(
            model_name='rent',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per month if rent type is Fixed or Index.', max_digits=12, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='rent',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Effective end date'),
        ),
        migrations.AddField(
            model_name='rent',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Effective start date'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='type',
            field=enumfields.fields.EnumField(default='fixed', enum=leasing.enums.RentType, max_length=255, verbose_name='Rent type'),
        ),
    ]
