# Generated by Django 2.0.3 on 2018-03-20 13:26

from django.db import migrations
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0005_add_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasearea',
            name='location',
            field=enumfields.fields.EnumField(enum=leasing.enums.LocationType, max_length=30, verbose_name='Location'),
        ),
    ]
