# Generated by Django 2.0.2 on 2018-02-19 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0005_add_plan_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('identifier', models.CharField(max_length=255, verbose_name='Identifier')),
                ('area', models.PositiveIntegerField(blank=True, null=True, verbose_name='Area')),
                ('cross_section', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cross section')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('postal_code', models.CharField(max_length=255, verbose_name='Postal code')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('registration_date', models.DateField(verbose_name='Registration date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlotExplanation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='plot',
            name='explanation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.PlotExplanation', verbose_name='Explanation'),
        ),
    ]
