# Generated by Django 2.0.2 on 2018-02-13 08:21

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import leasing.models.client


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0005_add_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', enumfields.fields.EnumField(enum=leasing.models.client.RoleType, max_length=10)),
                ('shares_numerator', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numerator')),
                ('shares_denominator', models.PositiveIntegerField(blank=True, null=True, verbose_name='Denominator')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('notification_method', models.CharField(blank=True, max_length=255, verbose_name='Ilmoitustapa')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasing.Client')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasing.Lease')),
                ('related_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_clients', to='leasing.Client')),
            ],
        ),
    ]
