# Generated by Django 2.0.5 on 2018-05-04 11:22

from django.db import migrations
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0005_fixedinitialyearrent_intended_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasetype',
            name='due_dates_position',
            field=enumfields.fields.EnumField(default='start_of_month', enum=leasing.enums.DueDatesPosition, max_length=30, verbose_name='Due dates position'),
        ),
    ]
