# Generated by Django 2.0.2 on 2018-02-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0006_add_plot'),
        ('leasing', '0005_add_tenant'),
    ]

    operations = [
    ]
