# Generated by Django 2.0.3 on 2018-03-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0006_enlarge_leasearea_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
    ]
