# Generated by Django 2.0.5 on 2018-05-18 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0006_add_due_dates_position_to_leasetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('billing_period_start_date', models.DateField(verbose_name='Billing period start date')),
                ('billing_period_end_date', models.DateField(verbose_name='Billing period end date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='receivable_type',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='share_denominator',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='share_numerator',
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='generated',
            field=models.BooleanField(default=False, verbose_name='Is automatically generated?'),
        ),
        migrations.AddField(
            model_name='invoicerow',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='leasing.Invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='invoicerow',
            name='receivable_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.ReceivableType', verbose_name='Receivable type'),
        ),
        migrations.AddField(
            model_name='invoicerow',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leasing.Tenant', verbose_name='Tenant'),
        ),
    ]
