# Generated by Django 2.0.2 on 2018-02-22 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0007_merge_20180220_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Contract rent')),
                ('basic_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Basic rent')),
                ('new_basic_year_rent', models.CharField(max_length=255, verbose_name='New basic year rent')),
                ('start_date', models.DateField(null=True, verbose_name='Start date')),
                ('end_date', models.DateField(null=True, verbose_name='End date')),
            ],
        ),
        migrations.CreateModel(
            name='DueDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='text')),
            ],
        ),
        migrations.CreateModel(
            name='FidexInitialYearRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bill amount')),
                ('start_date', models.DateField(null=True, verbose_name='Start date')),
                ('end_date', models.DateField(null=True, verbose_name='End date')),
            ],
        ),
        migrations.CreateModel(
            name='IndexAdjustedRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rent')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('calculation_factor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rent')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RentBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('bill_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bill amount')),
                ('basic_index', models.PositiveIntegerField(blank=True, null=True, verbose_name='Basic index')),
                ('basic_index_rounding', models.PositiveIntegerField(blank=True, null=True, verbose_name='Basic index rounding')),
                ('x_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='X value')),
                ('y_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Y value')),
                ('y_value_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='Y value start')),
                ('adjustment_start_date', models.DateField(null=True, verbose_name='Adjustment start date')),
                ('adjustment_end_date', models.DateField(null=True, verbose_name='Adjustment end date')),
                ('rent_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rent amount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentBillingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentChargedRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rent')),
                ('start_date', models.DateField(null=True, verbose_name='Start date')),
                ('end_date', models.DateField(null=True, verbose_name='End date')),
                ('difference', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Difference')),
                ('calendar_year_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Calendar year rent')),
            ],
        ),
        migrations.CreateModel(
            name='RentCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='km2')),
                ('index', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Index')),
                ('ekm2ind100', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='emk2ind100')),
                ('ekm2ind', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='emk2ind')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Percentage')),
                ('basic_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Basic rent')),
                ('starting_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Starting rent')),
            ],
        ),
        migrations.CreateModel(
            name='RentDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('start_date', models.DateField(null=True, verbose_name='Start date')),
                ('end_date', models.DateField(null=True, verbose_name='End date')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Discount amount')),
                ('amount_left', models.PositiveIntegerField(blank=True, null=True, verbose_name='Discount amount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentDiscountAmountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentDiscountRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentDiscountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentIndexIDNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentPaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('times_per_year', models.PositiveSmallIntegerField(verbose_name='Times paid per year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rentdiscount',
            name='amount_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.RentDiscountAmountType', verbose_name='Discount type'),
        ),
        migrations.AddField(
            model_name='rentdiscount',
            name='discount_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.RentDiscountType', verbose_name='Discount type'),
        ),
        migrations.AddField(
            model_name='rentdiscount',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.RentPurpose', verbose_name='Usage purpose'),
        ),
        migrations.AddField(
            model_name='rentdiscount',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.RentDiscountRule', verbose_name='Discount rule'),
        ),
        migrations.AddField(
            model_name='rentcriteria',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.RentPurpose', verbose_name='Usage purpose'),
        ),
        migrations.AddField(
            model_name='rentbasicinfo',
            name='billing_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.RentBillingType', verbose_name='Rent billing type'),
        ),
        migrations.AddField(
            model_name='rentbasicinfo',
            name='index_id_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='leasing.RentIndexIDNumber', verbose_name='Index ID number'),
        ),
        migrations.AddField(
            model_name='rentbasicinfo',
            name='rent_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='leasing.RentPeriod', verbose_name='Rent period'),
        ),
        migrations.AddField(
            model_name='rentbasicinfo',
            name='rent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.RentType', verbose_name='Rent type'),
        ),
        migrations.AddField(
            model_name='rent',
            name='basic_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.RentBasicInfo', verbose_name='Rent'),
        ),
        migrations.AddField(
            model_name='rent',
            name='charged_rents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent', to='leasing.RentChargedRent', verbose_name='Rent'),
        ),
        migrations.AddField(
            model_name='rent',
            name='contract_rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.ContractRent', verbose_name='Rent'),
        ),
        migrations.AddField(
            model_name='rent',
            name='criterias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.RentCriteria', verbose_name='Rent'),
        ),
        migrations.AddField(
            model_name='rent',
            name='index_adjusted_rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent', to='leasing.IndexAdjustedRent', verbose_name='Index checked rent'),
        ),
        migrations.AddField(
            model_name='rent',
            name='rent_discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.RentDiscount', verbose_name='Adjustment'),
        ),
        migrations.AddField(
            model_name='indexadjustedrent',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.RentPurpose', verbose_name='Usage purpose'),
        ),
        migrations.AddField(
            model_name='fidexinitialyearrent',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasing.RentBasicInfo', verbose_name='Rent'),
        ),
        migrations.AddField(
            model_name='duedate',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.RentBasicInfo', verbose_name='Rent'),
        ),
        migrations.AddField(
            model_name='contractrent',
            name='basic_rent_payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.RentPaymentType', verbose_name='Basic rent payment type'),
        ),
        migrations.AddField(
            model_name='contractrent',
            name='contract_rent_payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.RentPaymentType', verbose_name='Contract rent payment type'),
        ),
        migrations.AddField(
            model_name='contractrent',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.RentPurpose', verbose_name='Usage purpose'),
        ),
    ]
