# Generated by Django 2.0.3 on 2018-03-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0007_add_ordering_to_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_archived',
        ),
    ]
