# Generated by Django 2.2.12 on 2020-08-03 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
from enum import Enum


class LandUseContractTypeLegacy(Enum):
    """
    In Finnish: Maankäyttösopimus tyyppi
    """

    LAND_USE_AGREEMENT = "Land use agreement"
    AGREEMENT_ON_APPRECIATION = "Agreement on appreciation"
    NO_AGREEMENT = "No agreement"

    class Labels:
        LAND_USE_AGREEMENT = "Land Use Contract Type", "Land use agreement"
        AGREEMENT_ON_APPRECIATION = (
            "Land Use Contract Type",
            "Agreement on appreciation",
        )
        NO_AGREEMENT = "Land Use Contract Type", "No agreement"


class InfillDevelopmentCompensationStateLegacy(Enum):
    """
    In Finnish: Täydennysrakentamiskorvauksen neuvotteluvaihe
    """

    ONGOING = "ongoing"
    NEGOTIATING = "negotiating"
    DECISION = "decision"

    class Labels:
        ONGOING = "Infill development compensation", "Ongoing"
        NEGOTIATING = "Infill development compensation", "Negotiating"
        DECISION = "Infill development compensation", "Decision"


class LandUseAgreementLitigantContactTypeLegacy(Enum):
    """
    In Finnish: Maankäyttösopimuksen osapuolen yhteystiedon tyyppi
    """

    TENANT = "tenant"
    BILLING = "billing"

    class Labels:
        TENANT = "Land Use Agreement Litigant Contact Type", "Tenant"
        BILLING = "Land Use Agreement Litigant Contact Type", "Billing"


class DueDatesPositionLegacy(Enum):
    """
    In Finnish: Eräpäivän sijainti
    """

    START_OF_MONTH = "start_of_month"
    MIDDLE_OF_MONTH = "middle_of_month"

    class Labels:
        START_OF_MONTH = "Due dates position", "Start of month"
        MIDDLE_OF_MONTH = "Due dates position", "Middle of month"


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leasing", "0007_add_business_id_validator"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandUseAgreement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "estimated_completion_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Estimated completion year"
                    ),
                ),
                (
                    "estimated_introduction_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Estimated introduction year",
                    ),
                ),
                (
                    "project_area",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Project area",
                    ),
                ),
                (
                    "plan_reference_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Plan reference number",
                    ),
                ),
                (
                    "plan_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Plan number",
                    ),
                ),
                (
                    "plan_lawfulness_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Plan lawfulness date"
                    ),
                ),
                (
                    "state",
                    enumfields.fields.EnumField(
                        blank=True,
                        enum=InfillDevelopmentCompensationStateLegacy,
                        max_length=30,
                        null=True,
                        verbose_name="State",
                    ),
                ),
                (
                    "land_use_contract_type",
                    enumfields.fields.EnumField(
                        blank=True,
                        enum=LandUseContractTypeLegacy,
                        max_length=30,
                        null=True,
                        verbose_name="Contract type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Land use agreement",
                "verbose_name_plural": "Land use agreements",
            },
        ),
        migrations.CreateModel(
            name="LandUseAgreementCompensations",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "cash_compensation",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Cash compensation",
                    ),
                ),
                (
                    "land_compensation",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Land compensation",
                    ),
                ),
                (
                    "other_compensation",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Other compensation",
                    ),
                ),
                (
                    "first_installment_increase",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name=""
                    ),
                ),
                (
                    "street_acquisition_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name=""
                    ),
                ),
                ("street_area", models.PositiveIntegerField()),
                (
                    "park_acquisition_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name=""
                    ),
                ),
                ("park_area", models.PositiveIntegerField()),
                (
                    "other_acquisition_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name=""
                    ),
                ),
                ("other_area", models.PositiveIntegerField()),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="LandUseAgreementConditionType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="LandUseAgreementDefinition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="LandUseAgreementLitigant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "share_numerator",
                    models.PositiveIntegerField(verbose_name="Numerator"),
                ),
                (
                    "share_denominator",
                    models.PositiveIntegerField(verbose_name="Denominator"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Section"
                    ),
                ),
                (
                    "land_use_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="litigants",
                        to="leasing.LandUseAgreement",
                        verbose_name="Land use agreement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Land use agreement litigant",
                "verbose_name_plural": "Land use agreement litigant",
            },
        ),
        migrations.CreateModel(
            name="LandUseAgreementStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="LandUseAgreementType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "identifier",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Identifier"
                    ),
                ),
                (
                    "sap_material_code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SAP material code",
                    ),
                ),
                (
                    "sap_order_item_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SAP order item number",
                    ),
                ),
                (
                    "due_dates_position",
                    enumfields.fields.EnumField(
                        default="start_of_month",
                        enum=DueDatesPositionLegacy,
                        max_length=30,
                        verbose_name="Due dates position",
                    ),
                ),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.AlterField(
            model_name="contract",
            name="lease",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="leasing.Lease",
                verbose_name="Lease",
            ),
        ),
        migrations.CreateModel(
            name="LandUseAgreementLitigantContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "type",
                    enumfields.fields.EnumField(
                        blank=True,
                        enum=LandUseAgreementLitigantContactTypeLegacy,
                        max_length=30,
                        null=True,
                        verbose_name="Contact type",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End date"),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="land_use_agreement",
                        to="leasing.Contact",
                        verbose_name="Contact",
                    ),
                ),
                (
                    "land_use_agreement_litigant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="litigant_contacts",
                        to="leasing.LandUseAgreementLitigant",
                        verbose_name="Land use agreement litigant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Land use agreement litigant",
                "verbose_name_plural": "Land use agreement litigant",
            },
        ),
        migrations.CreateModel(
            name="LandUseAgreementIdentifier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(verbose_name="Sequence number"),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="leasing.District",
                        verbose_name="District",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="leasing.Municipality",
                        verbose_name="Municipality",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="leasing.LandUseAgreementType",
                        verbose_name="Land use agreement type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lease identifier",
                "verbose_name_plural": "Lease identifiers",
                "unique_together": {("type", "municipality", "district", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="LandUseAgreementEstate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "estate_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Estate id"
                    ),
                ),
                (
                    "land_use_agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estate_ids",
                        to="leasing.LandUseAgreement",
                        verbose_name="Land use agreement",
                    ),
                ),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="LandUseAgreementDecision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Reference number",
                    ),
                ),
                (
                    "decision_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Decision date"
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Section"
                    ),
                ),
                (
                    "decision_maker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="leasing.DecisionMaker",
                        verbose_name="Decision maker",
                    ),
                ),
                (
                    "land_use_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="leasing.LandUseAgreement",
                        verbose_name="Land use agreement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Land use agreement decision",
                "verbose_name_plural": "Land use agreement decisions",
            },
        ),
        migrations.CreateModel(
            name="LandUseAgreementCondition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name=" date"),
                ),
                (
                    "sent_date",
                    models.DateField(blank=True, null=True, verbose_name="Sent date"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "land_use_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conditions",
                        to="leasing.LandUseAgreement",
                        verbose_name="Land use agreement",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="leasing.LandUseAgreementConditionType",
                        verbose_name="Form of management",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="LandUseAgreementAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Postal code",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="City"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Is primary?"),
                ),
                (
                    "land_use_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="leasing.LandUseAgreement",
                        verbose_name="Land use agreement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Land use agreement address",
                "verbose_name_plural": "Land use agreement addresses",
            },
        ),
        migrations.AddField(
            model_name="landuseagreement",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.LandUseAgreementDefinition",
                verbose_name="Land use agreement definition",
            ),
        ),
        migrations.AddField(
            model_name="landuseagreement",
            name="identifier",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.LandUseAgreementIdentifier",
                verbose_name="Land use agreement identifier",
            ),
        ),
        migrations.AddField(
            model_name="landuseagreement",
            name="plan_acceptor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="land_use_agreements",
                to="leasing.DecisionMaker",
                verbose_name="Plan acceptor",
            ),
        ),
        migrations.AddField(
            model_name="landuseagreement",
            name="preparer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Preparer",
            ),
        ),
        migrations.AddField(
            model_name="landuseagreement",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.LandUseAgreementStatus",
                verbose_name="Land use agreement status",
            ),
        ),
        migrations.AddField(
            model_name="landuseagreement",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.LandUseAgreementType",
                verbose_name="Land use agreement type",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="land_use_agreement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="leasing.LandUseAgreement",
                verbose_name="Land use agreement",
            ),
        ),
    ]
