# Generated by Django 2.2.13 on 2020-08-21 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0008_land_use_agreement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landuseagreement",
            name="identifier",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="leasing.LandUseAgreementIdentifier",
                verbose_name="Land use agreement identifier",
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreement",
            name="preparer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Preparer",
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementcompensations",
            name="first_installment_increase",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name="First installment increase",
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementcompensations",
            name="other_acquisition_value",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Other acquisition value"
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementcompensations",
            name="park_acquisition_value",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Park acquisition value"
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementcompensations",
            name="street_acquisition_value",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Street acquisition value"
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementcondition",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Due date"),
        ),
    ]
