# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0008_auto_20170516_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseRealPropertyUnitDetailedPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detailed plan identification number')),
                ('description', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Description')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('state', enumfields.fields.EnumField(enum=leasing.enums.DetailedPlanState, max_length=255, verbose_name='State')),
                ('lease_property_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_plans', to='leasing.LeaseRealPropertyUnit')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseRealPropertyUnitPlotDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Plot division identification number')),
                ('description', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Description')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('state', enumfields.fields.EnumField(enum=leasing.enums.PlotDivisionState, max_length=255, verbose_name='State')),
                ('lease_property_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_divisions', to='leasing.LeaseRealPropertyUnit')),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='areas',
            field=models.ManyToManyField(blank=True, to='leasing.Area'),
        ),
        migrations.AlterField(
            model_name='application',
            name='notes',
            field=models.ManyToManyField(blank=True, to='leasing.Note'),
        ),
        migrations.AlterField(
            model_name='area',
            name='notes',
            field=models.ManyToManyField(blank=True, to='leasing.Note'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='areas',
            field=models.ManyToManyField(blank=True, to='leasing.Area'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='notes',
            field=models.ManyToManyField(blank=True, to='leasing.Note'),
        ),
    ]
