# Generated by Django 2.0.3 on 2018-03-22 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0008_remove_comment_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('supervision_date', models.DateField(blank=True, null=True, verbose_name='Supervision date')),
                ('supervised_date', models.DateField(blank=True, null=True, verbose_name='Supervised date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConditionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('contract_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contract number')),
                ('signing_date', models.DateField(blank=True, null=True, verbose_name='Signing date')),
                ('signing_note', models.TextField(blank=True, null=True, verbose_name='Signing note')),
                ('is_readjustment_decision', models.BooleanField(default=False, verbose_name='Is readjustment decision')),
                ('ktj_link', models.CharField(blank=True, max_length=1024, null=True, verbose_name='KTJ link')),
                ('collateral_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Collateral number')),
                ('collateral_start_date', models.DateField(blank=True, null=True, verbose_name='Collateral starting date')),
                ('collateral_end_date', models.DateField(blank=True, null=True, verbose_name='Collateral ending date')),
                ('collateral_note', models.TextField(blank=True, null=True, verbose_name='Collateral note')),
                ('institution_identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Institution identifier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signing_date', models.DateField(blank=True, null=True, verbose_name='Signing date')),
                ('sign_by_date', models.DateField(blank=True, null=True, verbose_name='Sign by date')),
                ('first_call_sent', models.DateField(blank=True, null=True, verbose_name='First call sent')),
                ('second_call_sent', models.DateField(blank=True, null=True, verbose_name='Second call sent')),
                ('third_call_sent', models.DateField(blank=True, null=True, verbose_name='Third call sent')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_changes', to='leasing.Contract', verbose_name='Contract')),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference number')),
                ('decision_date', models.DateField(blank=True, null=True, verbose_name='Decision date')),
                ('section', models.CharField(blank=True, max_length=255, null=True, verbose_name='Section')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecisionMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecisionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector', models.CharField(blank=True, max_length=255, null=True, verbose_name='Inspector')),
                ('supervision_date', models.DateField(blank=True, null=True, verbose_name='Supervision date')),
                ('supervised_date', models.DateField(blank=True, null=True, verbose_name='Supervised date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='leasing.Lease', verbose_name='Lease')),
            ],
        ),
        migrations.CreateModel(
            name='MortgageDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Number')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mortgage_documents', to='leasing.Contract', verbose_name='Contract')),
            ],
        ),
        migrations.AddField(
            model_name='decision',
            name='decision_maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='leasing.DecisionMaker', verbose_name='Decision maker'),
        ),
        migrations.AddField(
            model_name='decision',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='leasing.Lease', verbose_name='Lease'),
        ),
        migrations.AddField(
            model_name='decision',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.DecisionType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='contractchange',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leasing.Decision', verbose_name='Decision'),
        ),
        migrations.AddField(
            model_name='contract',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leasing.Decision', verbose_name='Decision'),
        ),
        migrations.AddField(
            model_name='contract',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='leasing.Lease', verbose_name='Lease'),
        ),
        migrations.AddField(
            model_name='contract',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.ContractType', verbose_name='Contract type'),
        ),
        migrations.AddField(
            model_name='condition',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conditions', to='leasing.Decision', verbose_name='Decision'),
        ),
        migrations.AddField(
            model_name='condition',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.ConditionType', verbose_name='Type'),
        ),
    ]
