# Generated by Django 2.0.3 on 2018-03-27 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leasing', '0009_add_contract_and_decision_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructabilityDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('type', enumfields.fields.EnumField(enum=leasing.enums.ConstructabilityType, max_length=30, verbose_name='Type')),
                ('text', models.TextField(verbose_name='Text')),
                ('ahjo_reference_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='AHJO reference number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='leasearea',
            name='constructability_report_geotechnical_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Constructability report geotechnical number'),
        ),
        migrations.AddField(
            model_name='leasearea',
            name='constructability_report_investigation_state',
            field=enumfields.fields.EnumField(blank=True, enum=leasing.enums.ConstructabilityReportInvestigationState, max_length=30, null=True, verbose_name='Constructability report investigation state'),
        ),
        migrations.AddField(
            model_name='leasearea',
            name='constructability_report_signer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Constructability report signer'),
        ),
        migrations.AddField(
            model_name='leasearea',
            name='constructability_report_signing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Constructability report signing date'),
        ),
        migrations.AddField(
            model_name='leasearea',
            name='constructability_report_state',
            field=enumfields.fields.EnumField(blank=True, enum=leasing.enums.ConstructabilityState, max_length=30, null=True, verbose_name='Constructability report state'),
        ),
        migrations.AddField(
            model_name='leasearea',
            name='demolition_state',
            field=enumfields.fields.EnumField(blank=True, enum=leasing.enums.ConstructabilityState, max_length=30, null=True, verbose_name='Demolition state'),
        ),
        migrations.AddField(
            model_name='leasearea',
            name='other_state',
            field=enumfields.fields.EnumField(blank=True, enum=leasing.enums.ConstructabilityState, max_length=30, null=True, verbose_name='Other state'),
        ),
        migrations.AddField(
            model_name='leasearea',
            name='polluted_land_matti_report_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Matti report number'),
        ),
        migrations.AddField(
            model_name='leasearea',
            name='polluted_land_planner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='leasearea',
            name='polluted_land_projectwise_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ProjectWise number'),
        ),
        migrations.AddField(
            model_name='leasearea',
            name='polluted_land_rent_condition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Polluted land rent condition date'),
        ),
        migrations.AddField(
            model_name='leasearea',
            name='polluted_land_rent_condition_state',
            field=enumfields.fields.EnumField(blank=True, enum=leasing.enums.PollutedLandRentConditionState, max_length=30, null=True, verbose_name='Polluted land rent condition state'),
        ),
        migrations.AddField(
            model_name='leasearea',
            name='polluted_land_state',
            field=enumfields.fields.EnumField(blank=True, enum=leasing.enums.ConstructabilityState, max_length=30, null=True, verbose_name='Polluted land state'),
        ),
        migrations.AddField(
            model_name='leasearea',
            name='preconstruction_state',
            field=enumfields.fields.EnumField(blank=True, enum=leasing.enums.ConstructabilityState, max_length=30, null=True, verbose_name='Preconstruction state'),
        ),
        migrations.AddField(
            model_name='constructabilitydescription',
            name='lease_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructability_descriptions', to='leasing.LeaseArea'),
        ),
        migrations.AddField(
            model_name='constructabilitydescription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
