# Generated by Django 2.0.5 on 2018-05-30 07:44

from django.db import migrations
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0009_multiple_addresses_for_land_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedlease',
            name='type',
            field=enumfields.fields.EnumField(blank=True, enum=leasing.enums.LeaseRelationType, max_length=30, null=True, verbose_name='Lease relation type'),
        ),
    ]
