# Generated by Django 2.0.2 on 2018-02-26 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0009_change_tenants_to_tenant_and_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=255, verbose_name='Contract number')),
                ('signing_date', models.DateField(verbose_name='Signing date')),
                ('signing_date_comment', models.TextField(verbose_name='Signing date comment')),
                ('ktj_document', models.CharField(max_length=255, verbose_name='Ktj document')),
                ('lease_deposit_number', models.CharField(max_length=255, verbose_name='Lease deposit number')),
                ('lease_deposit_starting_date', models.DateField(verbose_name='Lease deposit starting date')),
                ('lease_deposit_ending_date', models.DateField(verbose_name='Lease deposit ending date')),
                ('lease_deposit_comment', models.TextField(verbose_name='Lease deposit comment')),
                ('administration_number', models.CharField(max_length=255, verbose_name='Administration number')),
            ],
        ),
        migrations.CreateModel(
            name='ContractChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_signing_date', models.DateField(verbose_name='Modification signing date')),
                ('to_be_signed_by', models.DateField(verbose_name='To be signed by')),
                ('first_call_sent', models.DateField(verbose_name='First call sent')),
                ('second_call_sent', models.DateField(verbose_name='Second call sent')),
                ('third_call_sent', models.DateField(verbose_name='Third call sent')),
                ('modification_description', models.TextField(verbose_name='Modification description')),
            ],
        ),
        migrations.CreateModel(
            name='ContractLinkedRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractSetupDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector', models.CharField(max_length=255, verbose_name='Inspector')),
                ('supervision_date', models.DateField(verbose_name='Supervision date')),
                ('supervised_date', models.DateField(verbose_name='Supervised date')),
                ('inspection_description', models.TextField(verbose_name='Inspection description')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_date', models.DateField(verbose_name='Rule date')),
                ('rule_clause', models.CharField(max_length=255, verbose_name='Rule clause')),
                ('rule_description', models.TextField(verbose_name='Rule description')),
            ],
        ),
        migrations.CreateModel(
            name='RuleMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuleTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervision_date', models.DateField(verbose_name='Supervision date')),
                ('supervised_date', models.DateField(verbose_name='Supervised date')),
                ('term_description', models.TextField(verbose_name='Term description')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='leasing.Rule', verbose_name='Rule')),
            ],
        ),
        migrations.CreateModel(
            name='RuleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='ruleterm',
            name='term_purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leasing.TermPurpose', verbose_name='Term purpose'),
        ),
        migrations.AddField(
            model_name='rule',
            name='rule_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.RuleMaker', verbose_name='Rule maker'),
        ),
        migrations.AddField(
            model_name='rule',
            name='rule_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.RuleType', verbose_name='Rule type'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.ContractType', verbose_name='Contract type'),
        ),
        migrations.AddField(
            model_name='contract',
            name='linked_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.ContractLinkedRule', verbose_name='Linked rule'),
        ),
        migrations.AddField(
            model_name='contract',
            name='setup_decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.ContractSetupDecision', verbose_name='Setup decision'),
        ),
    ]
