# Generated by Django 2.0.2 on 2018-03-01 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0010_add_contract_and_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionInvestigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geotechnical_number', models.CharField(max_length=255, verbose_name='Geotechnical number')),
                ('signing_date', models.DateField(verbose_name='Signing date')),
                ('report_author', models.CharField(max_length=255, verbose_name='Report author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConstructionInvestigationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectwise_number', models.CharField(max_length=255, verbose_name='Rule clause')),
                ('matti_report', models.CharField(max_length=255, verbose_name='Matti report')),
                ('rent_condition_date', models.DateField(verbose_name='Rent condition date')),
                ('contamination_author', models.CharField(max_length=255, verbose_name='Contamination author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('AHJO_number', models.CharField(max_length=255, verbose_name='AHJO number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Demolition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leasing.Decision', verbose_name='Decision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leasing.Decision', verbose_name='Decision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preconstuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leasing.Decision', verbose_name='Decision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contamination',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leasing.Decision', verbose_name='Decision'),
        ),
        migrations.AddField(
            model_name='contamination',
            name='rent_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leasing.RentCondition', verbose_name='Rent conditions'),
        ),
        migrations.AddField(
            model_name='constructioninvestigation',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leasing.Decision', verbose_name='Decision'),
        ),
        migrations.AddField(
            model_name='constructioninvestigation',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leasing.ConstructionInvestigationReport', verbose_name='Report'),
        ),
    ]
