# Generated by Django 2.0.3 on 2018-04-05 10:24

from django.db import migrations
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0010_add_constructability_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeperiod',
            name='type',
            field=enumfields.fields.EnumField(enum=leasing.enums.NoticePeriodType, max_length=30, verbose_name='Period type'),
        ),
    ]
