# Generated by Django 2.2.13 on 2020-09-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0011_landuseagreementinvoice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plotsearchstage",
            options={
                "ordering": ["name"],
                "verbose_name": "Plot search stage",
                "verbose_name_plural": "Plot search stages",
            },
        ),
    ]
