# Generated by Django 2.0.4 on 2018-04-09 10:59

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0012_add_rent_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasisOfRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('detailed_plan_identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detailed plan identifier')),
                ('lease_rights_end_date', models.DateField(blank=True, null=True, verbose_name='Lease rights end date')),
                ('index', models.PositiveIntegerField(verbose_name='Index')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('financing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leasing.Financing', verbose_name='Form of financing')),
                ('management', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leasing.Management', verbose_name='Form of management')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasisOfRentDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, verbose_name='Identifier')),
                ('basis_of_rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='leasing.BasisOfRent')),
            ],
        ),
        migrations.CreateModel(
            name='BasisOfRentPlotType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasisOfRentPropertyIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, verbose_name='Identifier')),
                ('basis_of_rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_identifiers', to='leasing.BasisOfRent', verbose_name='Basis of rent')),
            ],
        ),
        migrations.CreateModel(
            name='BasisOfRentRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('period', enumfields.fields.EnumField(enum=leasing.enums.PeriodType, max_length=20, verbose_name='Period')),
                ('basis_of_rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_rates', to='leasing.BasisOfRent', verbose_name='Basis of rent')),
                ('intended_use', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leasing.RentIntendedUse', verbose_name='Intended use')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='basisofrent',
            name='plot_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.BasisOfRentPlotType', verbose_name='Plot type'),
        ),
    ]
