# Generated by Django 2.2.13 on 2020-08-31 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0012_fix_plot_search_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="areas",
                to="leasing.AreaSource",
                verbose_name="Source",
            ),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                fields=("type", "identifier", "external_id", "source"),
                name="leasing_area_type_identifier_externalid_source_key",
            ),
        ),
    ]
