# Generated by Django 2.0.6 on 2018-06-19 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0013_basis_of_rent_changes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areanote',
            options={'verbose_name': 'Area note', 'verbose_name_plural': 'Area notes'},
        ),
        migrations.AlterModelOptions(
            name='basisofrent',
            options={'verbose_name': 'Basis of rent', 'verbose_name_plural': 'Basis of rents'},
        ),
        migrations.AlterModelOptions(
            name='basisofrentbuildpermissiontype',
            options={'ordering': ['name'], 'verbose_name': 'Basis of rent build permission type', 'verbose_name_plural': 'Basis of rent build permission types'},
        ),
        migrations.AlterModelOptions(
            name='basisofrentdecision',
            options={'verbose_name': 'Basis of rent decision', 'verbose_name_plural': 'Basis of rent decisions'},
        ),
        migrations.AlterModelOptions(
            name='basisofrentplottype',
            options={'ordering': ['name'], 'verbose_name': 'Basis of rent plot type', 'verbose_name_plural': 'Basis of rent plot types'},
        ),
        migrations.AlterModelOptions(
            name='basisofrentpropertyidentifier',
            options={'verbose_name': 'Basis of rent property identifier', 'verbose_name_plural': 'Basis of rent property identifiers'},
        ),
        migrations.AlterModelOptions(
            name='basisofrentrate',
            options={'verbose_name': 'Basis of rent rate', 'verbose_name_plural': 'Basis of rent rates'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='commenttopic',
            options={'ordering': ['name'], 'verbose_name': 'Comment topic', 'verbose_name_plural': 'Comment topics'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name': 'Condition', 'verbose_name_plural': 'Conditions'},
        ),
        migrations.AlterModelOptions(
            name='conditiontype',
            options={'ordering': ['name'], 'verbose_name': 'Condition type', 'verbose_name_plural': 'Condition types'},
        ),
        migrations.AlterModelOptions(
            name='constructabilitydescription',
            options={'verbose_name': 'Constructability description', 'verbose_name_plural': 'Constructability descriptions'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['type', 'name', 'last_name', 'first_name'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterModelOptions(
            name='contractchange',
            options={'verbose_name': 'Contract change', 'verbose_name_plural': 'Contract changes'},
        ),
        migrations.AlterModelOptions(
            name='contractrent',
            options={'verbose_name': 'Contract rent', 'verbose_name_plural': 'Contract rents'},
        ),
        migrations.AlterModelOptions(
            name='contracttype',
            options={'ordering': ['name'], 'verbose_name': 'Basis of rent plot types', 'verbose_name_plural': 'Basis of rent plot types'},
        ),
        migrations.AlterModelOptions(
            name='decision',
            options={'verbose_name': 'Decision', 'verbose_name_plural': 'Decisions'},
        ),
        migrations.AlterModelOptions(
            name='decisionmaker',
            options={'ordering': ['name'], 'verbose_name': 'Decision maker', 'verbose_name_plural': 'Decision makers'},
        ),
        migrations.AlterModelOptions(
            name='decisiontype',
            options={'ordering': ['name'], 'verbose_name': 'Decision type', 'verbose_name_plural': 'Decision types'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('municipality__name', 'name'), 'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='fixedinitialyearrent',
            options={'verbose_name': 'Fixed initial year rent', 'verbose_name_plural': 'Fixed initial year rents'},
        ),
        migrations.AlterModelOptions(
            name='indexadjustedrent',
            options={'verbose_name': 'Index adjusted rent', 'verbose_name_plural': 'Index adjusted rents'},
        ),
        migrations.AlterModelOptions(
            name='inspection',
            options={'verbose_name': 'Inspection', 'verbose_name_plural': 'Inspections'},
        ),
        migrations.AlterModelOptions(
            name='intendeduse',
            options={'ordering': ['name'], 'verbose_name': 'Intended use', 'verbose_name_plural': 'Intended uses'},
        ),
        migrations.AlterModelOptions(
            name='invoicerow',
            options={'verbose_name': 'Invoice row', 'verbose_name_plural': 'Invoice rows'},
        ),
        migrations.AlterModelOptions(
            name='lease',
            options={'permissions': (('view_lease', 'Can view lease'),), 'verbose_name': 'Lease', 'verbose_name_plural': 'Leases'},
        ),
        migrations.AlterModelOptions(
            name='leasearea',
            options={'verbose_name': 'Lease area', 'verbose_name_plural': 'Lease areas'},
        ),
        migrations.AlterModelOptions(
            name='leaseareaaddress',
            options={'verbose_name': 'Lease area address', 'verbose_name_plural': 'Lease area addresses'},
        ),
        migrations.AlterModelOptions(
            name='leasebasisofrent',
            options={'verbose_name': 'Lease basis of rent', 'verbose_name_plural': 'Lease basis of rents'},
        ),
        migrations.AlterModelOptions(
            name='leaseidentifier',
            options={'verbose_name': 'Lease identifier', 'verbose_name_plural': 'Lease identifiers'},
        ),
        migrations.AlterModelOptions(
            name='leasestatelog',
            options={'verbose_name': 'Lease state log', 'verbose_name_plural': 'Lease state logs'},
        ),
        migrations.AlterModelOptions(
            name='leasetype',
            options={'ordering': ['name'], 'verbose_name': 'Lease type', 'verbose_name_plural': 'Lease types'},
        ),
        migrations.AlterModelOptions(
            name='mortgagedocument',
            options={'verbose_name': 'Mortgage document', 'verbose_name_plural': 'Mortgage documents'},
        ),
        migrations.AlterModelOptions(
            name='noticeperiod',
            options={'ordering': ['name'], 'verbose_name': 'Notice period', 'verbose_name_plural': 'Notice periods'},
        ),
        migrations.AlterModelOptions(
            name='payablerent',
            options={'verbose_name': 'Payable rent', 'verbose_name_plural': 'Payable rents'},
        ),
        migrations.AlterModelOptions(
            name='planunit',
            options={'verbose_name': 'Plan unit', 'verbose_name_plural': 'Plan units'},
        ),
        migrations.AlterModelOptions(
            name='planunitaddress',
            options={'verbose_name': 'Plan unit address', 'verbose_name_plural': 'Plan unit addresses'},
        ),
        migrations.AlterModelOptions(
            name='planunitintendeduse',
            options={'ordering': ['name'], 'verbose_name': 'Plan unit intended use', 'verbose_name_plural': 'Plan unit intended uses'},
        ),
        migrations.AlterModelOptions(
            name='planunitstate',
            options={'ordering': ['name'], 'verbose_name': 'Plan unit state', 'verbose_name_plural': 'Plan unit states'},
        ),
        migrations.AlterModelOptions(
            name='planunittype',
            options={'ordering': ['name'], 'verbose_name': 'Plan unit type', 'verbose_name_plural': 'Plan unit types'},
        ),
        migrations.AlterModelOptions(
            name='plot',
            options={'verbose_name': 'Plot', 'verbose_name_plural': 'Plots'},
        ),
        migrations.AlterModelOptions(
            name='plotaddress',
            options={'verbose_name': 'Plot address', 'verbose_name_plural': 'Plot addresses'},
        ),
        migrations.AlterModelOptions(
            name='plotdivisionstate',
            options={'ordering': ['name'], 'verbose_name': 'Plot divisions state', 'verbose_name_plural': 'Plot division states'},
        ),
        migrations.AlterModelOptions(
            name='relatedlease',
            options={'verbose_name': 'Related lease', 'verbose_name_plural': 'Related leases'},
        ),
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'Rent', 'verbose_name_plural': 'Rents'},
        ),
        migrations.AlterModelOptions(
            name='rentadjustment',
            options={'verbose_name': 'Rent adjustment', 'verbose_name_plural': 'Rent adjustments'},
        ),
        migrations.AlterModelOptions(
            name='rentduedate',
            options={'verbose_name': 'Rent due date', 'verbose_name_plural': 'Rent due dates'},
        ),
        migrations.AlterModelOptions(
            name='rentintendeduse',
            options={'ordering': ['name'], 'verbose_name': 'Rent intended use', 'verbose_name_plural': 'Rent intended uses'},
        ),
        migrations.AlterModelOptions(
            name='statisticaluse',
            options={'ordering': ['name'], 'verbose_name': 'Statistical use', 'verbose_name_plural': 'Statistical uses'},
        ),
        migrations.AlterModelOptions(
            name='supportivehousing',
            options={'ordering': ['name'], 'verbose_name': 'Supportive housing', 'verbose_name_plural': 'Supportive housings'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.AlterModelOptions(
            name='tenantcontact',
            options={'verbose_name': 'Tenant contact', 'verbose_name_plural': 'Tenant contacts'},
        ),
    ]
