# Generated by Django 2.2.13 on 2020-09-03 08:04

from django.db import migrations, models


def _generate_identifier(lease_identifier):
    """Returns the lease identifier as a string
    The lease identifier is constructed out of type, municipality,
    district, and sequence, in that order. For example, the identifier
    for a residence (A1) in Helsinki (1), Vallila (22), and sequence
    number 1 would be A1122-1.
    """
    return "{}{}{:02}-{}".format(
        lease_identifier.type.identifier,
        lease_identifier.municipality.identifier,
        int(lease_identifier.district.identifier),
        lease_identifier.sequence,
    )


def forwards_func(apps, schema_editor):
    LeaseIdentifier = apps.get_model("leasing", "LeaseIdentifier")  # NOQA: N806

    for lease_identifier in LeaseIdentifier.objects.all():
        lease_identifier.identifier = _generate_identifier(lease_identifier)
        lease_identifier.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0013_reform_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaseidentifier",
            name="identifier",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Identifier"
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
