# Generated by Django 2.2.13 on 2020-09-04 06:26

import enumfields.fields
from django.db import migrations

import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0014_add_lease_identifier_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="planunit",
            name="plan_unit_status",
            field=enumfields.fields.EnumField(
                default="present",
                enum=leasing.enums.PlanUnitStatus,
                max_length=30,
                verbose_name="Plan unit status",
            ),
        ),
    ]
