# Generated by Django 2.0.6 on 2018-06-19 05:54

from django.db import migrations, models
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0014_add_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrent',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Base amount'),
        ),
        migrations.AlterField(
            model_name='contractrent',
            name='base_amount_period',
            field=enumfields.fields.EnumField(blank=True, enum=leasing.enums.PeriodType, max_length=30, null=True, verbose_name='Base amount period'),
        ),
    ]
