# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0014_auto_20170607_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='share',
        ),
        migrations.AddField(
            model_name='tenant',
            name='share_denominator',
            field=models.IntegerField(default=1, verbose_name='Denominator for the share of the rent'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='share_numerator',
            field=models.IntegerField(default=1, verbose_name='Numerator for the share of the rent'),
        ),
    ]
