# Generated by Django 2.0.6 on 2018-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0015_make_contract_rent_base_amount_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing_period_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Billing period end date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_period_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Billing period start date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sap_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SAP ID'),
        ),
        migrations.AlterField(
            model_name='invoicerow',
            name='billing_period_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Billing period end date'),
        ),
        migrations.AlterField(
            model_name='invoicerow',
            name='billing_period_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Billing period start date'),
        ),
    ]
