# Generated by Django 2.2.13 on 2020-09-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0015_planunit_plan_unit_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="landuseagreement",
            name="district",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.District",
                verbose_name="District",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landuseagreement",
            name="municipality",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.Municipality",
                verbose_name="Municipality",
            ),
            preserve_default=False,
        ),
    ]
