# Generated by Django 2.2.13 on 2020-09-23 06:53

import django.db.models.deletion
import enumfields.fields
from django.db import migrations, models

import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0016_land_use_agreement_add_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlotSearchTarget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    enumfields.fields.EnumField(
                        default="searchable",
                        enum=leasing.enums.PlotSearchTargetType,
                        max_length=30,
                        verbose_name="Target type",
                    ),
                ),
                (
                    "plan_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leasing.PlanUnit",
                    ),
                ),
                (
                    "plot_search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leasing.PlotSearch",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plotsearch",
            name="targets",
            field=models.ManyToManyField(
                through="leasing.PlotSearchTarget", to="leasing.PlanUnit"
            ),
        ),
    ]
