# Generated by Django 2.0.6 on 2018-07-04 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import leasing.enums
import leasing.models.infill_development_compensation


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leasing', '0017_invoice_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfillDevelopmentCompensation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference number')),
                ('detailed_plan_identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detailed plan identifier')),
                ('state', enumfields.fields.EnumField(blank=True, enum=leasing.enums.InfillDevelopmentCompensationState, max_length=30, null=True, verbose_name='State')),
                ('lease_contract_change_date', models.DateField(blank=True, null=True, verbose_name='Lease contract change date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Infill development compensation',
                'verbose_name_plural': 'Infill development compensations',
            },
        ),
        migrations.CreateModel(
            name='InfillDevelopmentCompensationAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('file', models.FileField(upload_to=leasing.models.infill_development_compensation.get_attachment_file_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Time uploaded')),
            ],
            options={
                'verbose_name': 'Infill development compensation attachment',
                'verbose_name_plural': 'Infill development compensation attachments',
            },
        ),
        migrations.CreateModel(
            name='InfillDevelopmentCompensationDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference number')),
                ('decision_date', models.DateField(blank=True, null=True, verbose_name='Decision date')),
                ('section', models.CharField(blank=True, max_length=255, null=True, verbose_name='Section')),
                ('decision_maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='infill_development_compensation_decisions', to='leasing.DecisionMaker', verbose_name='Decision maker')),
            ],
            options={
                'verbose_name': 'Infill development compensation decision',
                'verbose_name_plural': 'Infill development compensation decisions',
            },
        ),
        migrations.CreateModel(
            name='InfillDevelopmentCompensationIntendedUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('floor_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Floor m2')),
                ('amount_per_floor_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount per floor m^2')),
            ],
            options={
                'verbose_name': 'Infill development compensation intended use',
                'verbose_name_plural': 'Infill development compensation intended uses',
            },
        ),
        migrations.CreateModel(
            name='InfillDevelopmentCompensationLease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('monetary_compensation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monetary compensation amount')),
                ('compensation_investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Compensation investment amount')),
                ('increase_in_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Increase in value')),
                ('part_of_the_increase_in_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Part of the increase in value')),
                ('discount_in_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount in rent')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year')),
                ('sent_to_sap_date', models.DateField(blank=True, null=True, verbose_name='Sent to SAP date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid date')),
                ('infill_development_compensation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infill_development_compensation_leases', to='leasing.InfillDevelopmentCompensation', verbose_name='Infill development compensation')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infill_development_compensation_leases', to='leasing.Lease', verbose_name='Lease')),
            ],
            options={
                'verbose_name': 'Infill development compensation lease',
                'verbose_name_plural': 'Infill development compensation leases',
            },
        ),
        migrations.AlterModelOptions(
            name='invoicerow',
            options={'verbose_name': 'Invoice row', 'verbose_name_plural': 'Invoice rows'},
        ),
        migrations.AddField(
            model_name='infilldevelopmentcompensationintendeduse',
            name='infill_development_compensation_lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intended_uses', to='leasing.InfillDevelopmentCompensationLease', verbose_name='Infill development compensation lease'),
        ),
        migrations.AddField(
            model_name='infilldevelopmentcompensationintendeduse',
            name='intended_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leasing.IntendedUse', verbose_name='Intended use'),
        ),
        migrations.AddField(
            model_name='infilldevelopmentcompensationdecision',
            name='infill_development_compensation_lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='leasing.InfillDevelopmentCompensationLease', verbose_name='Infill development compensation lease'),
        ),
        migrations.AddField(
            model_name='infilldevelopmentcompensationattachment',
            name='infill_development_compensation_lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='leasing.InfillDevelopmentCompensationLease', verbose_name='Infill development compensation lease'),
        ),
        migrations.AddField(
            model_name='infilldevelopmentcompensationattachment',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AddField(
            model_name='infilldevelopmentcompensation',
            name='leases',
            field=models.ManyToManyField(related_name='leases', through='leasing.InfillDevelopmentCompensationLease', to='leasing.Lease'),
        ),
        migrations.AddField(
            model_name='infilldevelopmentcompensation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infill_development_compensations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
