# Generated by Django 2.1 on 2018-08-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0018_add_infill_development_compensation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lease',
            options={'verbose_name': 'Lease', 'verbose_name_plural': 'Leases'},
        ),
    ]
