# Generated by Django 2.2.13 on 2020-10-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0019_planunittargets_unique_planunit"),
    ]

    operations = [
        migrations.AddField(
            model_name="leasearea",
            name="is_master",
            field=models.BooleanField(default=False, verbose_name="Is master?"),
        ),
        migrations.AddField(
            model_name="planunit",
            name="is_master",
            field=models.BooleanField(default=False, verbose_name="Is master?"),
        ),
        migrations.AddField(
            model_name="plot",
            name="is_master",
            field=models.BooleanField(default=False, verbose_name="Is master?"),
        ),
        migrations.RunSQL(
            sql="UPDATE leasing_planunit SET is_master = TRUE WHERE in_contract = FALSE",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="UPDATE leasing_plot SET is_master = TRUE WHERE in_contract = FALSE",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
