# Generated by Django 2.1 on 2018-08-14 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0019_remove_view_lease_from_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='seasonal_end_day',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Seasonal end day'),
        ),
        migrations.AddField(
            model_name='rent',
            name='seasonal_end_month',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Seasonal end month'),
        ),
        migrations.AddField(
            model_name='rent',
            name='seasonal_start_day',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Seasonal start day'),
        ),
        migrations.AddField(
            model_name='rent',
            name='seasonal_start_month',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Seasonal start month'),
        ),
    ]
