# Generated by Django 2.2.13 on 2020-10-19 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0020_add_master_field_to_land"),
    ]

    operations = [
        migrations.RemoveField(model_name="plotsearch", name="type",),
        migrations.RunSQL(
            "DELETE FROM leasing_plotsearchtype;", reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "DELETE FROM leasing_plotsearchsubtype;", reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AddField(
            model_name="plotsearchsubtype",
            name="plot_search_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="leasing.PlotSearchType"
            ),
        ),
    ]
