# Generated by Django 2.1 on 2018-08-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0020_add_seasonal_dates_to_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasearea',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time archived'),
        ),
        migrations.AddField(
            model_name='leasearea',
            name='archived_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leasing.Decision', verbose_name='Archive decision'),
        ),
        migrations.AddField(
            model_name='leasearea',
            name='archived_note',
            field=models.TextField(blank=True, null=True, verbose_name='Archived note'),
        ),
    ]
