# Generated by Django 2.1 on 2018-09-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0021_add_archived_to_leasearea'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('reference_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Reference rate')),
                ('penalty_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Penalty rate')),
            ],
            options={
                'verbose_name': 'Interest rate',
                'verbose_name_plural': 'Interest rates',
            },
        ),
    ]
