# Generated by Django 2.1.1 on 2018-09-07 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import leasing.models.debt_collection


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leasing', '0022_interestrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCourtDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('file', models.FileField(upload_to=leasing.models.debt_collection.get_collection_court_decision_file_upload_to, verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Time uploaded')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_court_decisions', to='leasing.Lease', verbose_name='Lease')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Uploader')),
            ],
            options={
                'verbose_name': 'Collection court decision',
                'verbose_name_plural': 'Collection court decisions',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('file', models.FileField(upload_to=leasing.models.debt_collection.get_collection_letter_file_upload_to, verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Time uploaded')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_letters', to='leasing.Lease', verbose_name='Lease')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Uploader')),
            ],
            options={
                'verbose_name': 'Collection letter',
                'verbose_name_plural': 'Collection letters',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionLetterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('file', models.FileField(upload_to='collection_letter_templates/', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Collection letter template',
                'verbose_name_plural': 'Collection letter templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollectionNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_notes', to='leasing.Lease', verbose_name='Lease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Collection letter note',
                'verbose_name_plural': 'Collection letter notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
