# Generated by Django 2.2.13 on 2020-11-18 15:09

from enum import Enum
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class LandUseAgreementLitigantContactTypeLegacy(Enum):
    """
    In Finnish: Maankäyttösopimuksen osapuolen yhteystiedon tyyppi
    """

    TENANT = "tenant"
    BILLING = "billing"

    class Labels:
        TENANT = "Land Use Agreement Litigant Contact Type", "Tenant"
        BILLING = "Land Use Agreement Litigant Contact Type", "Billing"


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0023_remove_area_deleted"),
    ]

    operations = [
        migrations.RunSQL(
            "DELETE FROM leasing_landuseagreementlitigantcontact lc WHERE lc.type = NULL OR lc.contact_id = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterModelOptions(
            name="landuseagreementlitigant",
            options={
                "verbose_name": "Land use agreement litigant",
                "verbose_name_plural": "Land use agreement litigants",
            },
        ),
        migrations.AlterModelOptions(
            name="landuseagreementlitigantcontact",
            options={
                "verbose_name": "Land use agreement litigant",
                "verbose_name_plural": "Land use agreement litigants",
            },
        ),
        migrations.RemoveField(
            model_name="landuseagreementcondition",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="landuseagreementcondition",
            name="sent_date",
        ),
        migrations.AddField(
            model_name="landuseagreementcondition",
            name="supervised_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Supervised date"
            ),
        ),
        migrations.AddField(
            model_name="landuseagreementcondition",
            name="supervision_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Supervision date"
            ),
        ),
        migrations.AddField(
            model_name="landuseagreementlitigant",
            name="contacts",
            field=models.ManyToManyField(
                related_name="litigants",
                through="leasing.LandUseAgreementLitigantContact",
                to="leasing.Contact",
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementlitigantcontact",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="leasing.Contact",
                verbose_name="Contact",
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementlitigantcontact",
            name="land_use_agreement_litigant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="leasing.LandUseAgreementLitigant",
                verbose_name="Land use agreement litigant",
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementlitigantcontact",
            name="type",
            field=enumfields.fields.EnumField(
                enum=LandUseAgreementLitigantContactTypeLegacy,
                max_length=30,
                verbose_name="Contact type",
            ),
        ),
    ]
