# Generated by Django 2.1.1 on 2018-09-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0023_collectioncourtdecision_collectionletter_collectionlettertemplate_collectionnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracttype',
            options={'ordering': ['name'], 'verbose_name': 'Contract type', 'verbose_name_plural': 'Contract types'},
        ),
    ]
