# Generated by Django 2.2.13 on 2020-12-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0025_landuseagreement_improvements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landuseagreementestate",
            name="estate_id",
            field=models.CharField(max_length=50, verbose_name="Estate id"),
        ),
    ]
