# Generated by Django 2.1.1 on 2018-09-27 10:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0026_land_area_tweaks'),
    ]

    operations = [
        migrations.AddField(
            model_name='basisofrent',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geometry'),
        ),
        migrations.AddField(
            model_name='basisofrentpropertyidentifier',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geometry'),
        ),
        migrations.AddField(
            model_name='infilldevelopmentcompensation',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geometry'),
        ),
        migrations.AddField(
            model_name='leasearea',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geometry'),
        ),
        migrations.AddField(
            model_name='planunit',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geometry'),
        ),
        migrations.AddField(
            model_name='plot',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geometry'),
        ),
    ]
