# Generated by Django 2.2.13 on 2020-12-10 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_add_translations'),
        ('leasing', '0026_land_use_agreement_estate_remove_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotsearch',
            name='form',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.Form'),
        ),
    ]
