# Generated by Django 2.2.13 on 2021-01-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0027_change_rent_base_fields_required"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="landuseagreementidentifier",
            options={
                "verbose_name": "Land use agreement identifier",
                "verbose_name_plural": "Land use agreement identifiers",
            },
        ),
        migrations.RemoveField(
            model_name="landuseagreementtype", name="due_dates_position",
        ),
        migrations.RemoveField(
            model_name="landuseagreementtype", name="sap_material_code",
        ),
        migrations.RemoveField(
            model_name="landuseagreementtype", name="sap_order_item_number",
        ),
        migrations.AlterField(
            model_name="landuseagreementtype",
            name="identifier",
            field=models.CharField(max_length=255, verbose_name="Identifier"),
        ),
    ]
