# Generated by Django 2.1.1 on 2018-10-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0028_remove_rent_y_value_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='y_value_start',
            field=models.DateField(blank=True, null=True, verbose_name='Y value start date'),
        ),
    ]
