# Generated by Django 2.1.2 on 2018-10-25 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0029_add_rent_y_value_start_as_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='credited_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_invoices', to='leasing.Invoice', verbose_name='Credited invoice'),
        ),
    ]
