# Generated by Django 2.2.13 on 2021-02-18 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import leasing.enums
import leasing.models.land_use_agreement


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leasing", "0030_landuseagreement_plots"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandUseAgreementAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "type",
                    enumfields.fields.EnumField(
                        enum=leasing.enums.LandUseAgreementAttachmentType,
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=leasing.models.land_use_agreement.get_attachment_file_upload_to
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time uploaded"
                    ),
                ),
                (
                    "land_use_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="leasing.LandUseAgreement",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Land use agreement attachment",
                "verbose_name_plural": "Land use agreement attachments",
            },
        ),
    ]
