# Generated by Django 2.2.13 on 2021-02-18 08:35

from enum import Enum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


def get_landuse_agreement_attachment_file_upload_to(instance, filename):
    return "/".join(
        [
            "land_use_agreement_attachments",
            str(instance.land_use_agreement.id),
            filename,
        ]
    )


class LandUseAgreementAttachmentTypeLegacy(Enum):
    """
    In Finnish: Maankäyttösopimuksen liitetiedoston tyyppi
    """

    GENERAL = "general"
    COMPENSATION_CALCULATION = "compensation_calculation"

    class Labels:
        GENERAL = "Land use agreement attachment type", "General"
        COMPENSATION_CALCULATION = (
            "Land use agreement attachment type",
            "Compensation calculation",
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leasing", "0030_landuseagreement_plots"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandUseAgreementAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "type",
                    enumfields.fields.EnumField(
                        enum=LandUseAgreementAttachmentTypeLegacy,
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=get_landuse_agreement_attachment_file_upload_to,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time uploaded"
                    ),
                ),
                (
                    "land_use_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="leasing.LandUseAgreement",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Land use agreement attachment",
                "verbose_name_plural": "Land use agreement attachments",
            },
        ),
    ]
