# Generated by Django 2.1.3 on 2018-11-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0031_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='adjusted_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Adjusted due date'),
        ),
    ]
