# Generated by Django 2.1.3 on 2018-11-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0032_invoice_adjusted_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sap_sales_office',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SAP sales office'),
        ),
    ]
