# Generated by Django 2.1.3 on 2018-11-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0033_contact_sap_sales_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='reference',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Reference'),
        ),
    ]
