# Generated by Django 2.2.13 on 2021-02-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0034_remove_char_null_landuseagreement"),
    ]

    operations = [
        migrations.AddField(
            model_name="landuseagreementcompensations",
            name="land_use_agreement",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compensations",
                to="leasing.LandUseAgreement",
                verbose_name="Land use agreement",
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementcompensations",
            name="cash_compensation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Cash compensation",
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementcompensations",
            name="first_installment_increase",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="First installment increase",
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementcompensations",
            name="land_compensation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Land compensation",
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementcompensations",
            name="other_acquisition_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Other acquisition value",
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementcompensations",
            name="other_area",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementcompensations",
            name="other_compensation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Other compensation",
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementcompensations",
            name="park_acquisition_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Park acquisition value",
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementcompensations",
            name="park_area",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementcompensations",
            name="street_acquisition_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Street acquisition value",
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementcompensations",
            name="street_area",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
