# Generated by Django 2.1.3 on 2018-11-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0034_limit_tenant_reference_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='manual_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Manual ratio'),
        ),
        migrations.AddField(
            model_name='rent',
            name='manual_ratio_previous',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Manual ratio (previous)'),
        ),
    ]
