# Generated by Django 2.1.3 on 2018-11-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0036_redo_lease_basis_of_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasebasisofrent',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time archived'),
        ),
        migrations.AddField(
            model_name='leasebasisofrent',
            name='archived_note',
            field=models.TextField(blank=True, null=True, verbose_name='Archived note'),
        ),
    ]
