# Generated by Django 2.1.5 on 2019-02-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0038_invoicepayment_filing_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'ordering': ('-year', '-month'), 'verbose_name': 'Index', 'verbose_name_plural': 'Indexes'},
        ),
    ]
