# Generated by Django 2.1.5 on 2019-02-11 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0040_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Number')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total amount')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid date')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='Returned date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Collateral',
                'verbose_name_plural': 'Collaterals',
            },
        ),
        migrations.CreateModel(
            name='CollateralType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Collateral type',
                'verbose_name_plural': 'Collateral types',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contract',
            name='collateral_end_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='collateral_note',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='collateral_number',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='collateral_start_date',
        ),
        migrations.AddField(
            model_name='collateral',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaterals', to='leasing.Contract', verbose_name='Contract'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leasing.CollateralType', verbose_name='Collateral type'),
        ),
    ]
