# Generated by Django 2.1.5 on 2019-02-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0041_add_collateral'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='first_call_sent',
            field=models.DateField(blank=True, null=True, verbose_name='First call sent'),
        ),
        migrations.AddField(
            model_name='contract',
            name='second_call_sent',
            field=models.DateField(blank=True, null=True, verbose_name='Second call sent'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sign_by_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sign by date'),
        ),
        migrations.AddField(
            model_name='contract',
            name='third_call_sent',
            field=models.DateField(blank=True, null=True, verbose_name='Third call sent'),
        ),
    ]
