# Generated by Django 2.1.5 on 2019-02-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0043_remove_mortgage_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructabilitydescription',
            name='is_static',
            field=models.BooleanField(default=False, verbose_name='Is static?'),
        ),
        migrations.AddField(
            model_name='leasearea',
            name='preconstruction_estimated_construction_readiness_moment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preconstruction estimated construction readiness'),
        ),
        migrations.AddField(
            model_name='leasearea',
            name='preconstruction_inspection_moment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preconstruction inspection'),
        ),
    ]
