# Generated by Django 2.1.5 on 2019-02-12 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0044_additional_preconstruction_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Special project',
                'verbose_name_plural': 'Special projects',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lease',
            name='building_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Building selling price'),
        ),
        migrations.AddField(
            model_name='lease',
            name='conveyance_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Conveyance number'),
        ),
        migrations.AddField(
            model_name='lease',
            name='real_estate_developer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Real estate developer'),
        ),
        migrations.AddField(
            model_name='lease',
            name='special_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leasing.SpecialProject', verbose_name='Special project'),
        ),
    ]
