# Generated by Django 2.1.7 on 2019-02-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0046_additional_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='planunit',
            name='plot_division_effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='Plot division effective date'),
        ),
    ]
