# Generated by Django 2.1.7 on 2019-02-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0048_lease_field_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='arrangement_decision',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Arrangement decision'),
        ),
    ]
