# Generated by Django 3.2.10 on 2021-12-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0048_alter_jsonfields_to_new_jsonfields"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="district",
            name="name_fi",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="district",
            name="name_sv",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="financing",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="financing",
            name="name_fi",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="financing",
            name="name_sv",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="hitas",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="hitas",
            name="name_fi",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="hitas",
            name="name_sv",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="intendeduse",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="intendeduse",
            name="name_fi",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="intendeduse",
            name="name_sv",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="leaseareaaddress",
            name="address_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="leaseareaaddress",
            name="address_fi",
            field=models.CharField(max_length=255, null=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="leaseareaaddress",
            name="address_sv",
            field=models.CharField(max_length=255, null=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="management",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="management",
            name="name_fi",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="management",
            name="name_sv",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="municipality",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="municipality",
            name="name_fi",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="municipality",
            name="name_sv",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
    ]
