# Generated by Django 3.2.13 on 2022-07-11 10:09

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0049_add_translations"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomArea",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                ("rent_build_permission", models.IntegerField()),
                ("area", models.IntegerField()),
                ("section_area", models.IntegerField()),
                ("detailed_plan", models.CharField(max_length=255)),
                (
                    "state",
                    enumfields.fields.EnumField(
                        blank=True,
                        enum=leasing.enums.InfillDevelopmentCompensationState,
                        max_length=30,
                        null=True,
                        verbose_name="State",
                    ),
                ),
                (
                    "detailed_plan_identifier",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Detailed plan identifier",
                    ),
                ),
                (
                    "detailed_plan_latest_processing_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Detailed plan latest processing date",
                    ),
                ),
                (
                    "detailed_plan_latest_processing_date_note",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Note for latest processing date",
                    ),
                ),
                (
                    "intended_use",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leasing.planunitintendeduse",
                    ),
                ),
                (
                    "lease_area",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_area",
                        to="leasing.leasearea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UtilDistribution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distribution", models.IntegerField()),
                ("build_permission", models.CharField(max_length=255)),
                ("note", models.TextField()),
                (
                    "custom_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="util_distributions",
                        to="leasing.customarea",
                    ),
                ),
            ],
        ),
    ]
