# Generated by Django 2.1.7 on 2019-02-19 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leasing', '0049_arrangement_decision_default_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('key', models.CharField(max_length=255, verbose_name='Key')),
                ('value', models.TextField(verbose_name='Value')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'UI Datum',
                'verbose_name_plural': 'UI Data',
                'permissions': (('edit_global_ui_data', 'Can create, edit and delete global UI data'),),
            },
        ),
        migrations.AlterUniqueTogether(
            name='uidata',
            unique_together={('user', 'key')},
        ),
        # Add manual unique constraints because PostgreSQL considers every null as unique
        migrations.RunSQL(
            'CREATE UNIQUE INDEX "leasing_uidata_2col_uniq_idx" ON "leasing_uidata" ("user_id", "key") WHERE "user_id" IS NOT NULL;',
            'DROP INDEX IF EXISTS "leasing_uidata_2col_uniq_idx"'
        ),
        migrations.RunSQL(
            'CREATE UNIQUE INDEX "leasing_uidata_1col_uniq_idx" ON "leasing_uidata" ("key") WHERE "user_id" IS NULL;',
            'DROP INDEX IF EXISTS "leasing_uidata_1col_uniq_idx"'
        )
    ]
