# Generated by Django 2.1.7 on 2019-02-26 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import leasing.enums
import leasing.models.land_area


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leasing', '0050_ui_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseAreaAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('type', enumfields.fields.EnumField(enum=leasing.enums.LeaseAreaAttachmentType, max_length=30, verbose_name='Type')),
                ('file', models.FileField(upload_to=leasing.models.land_area.get_attachment_file_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Time uploaded')),
            ],
            options={
                'verbose_name': 'Lease area attachment',
                'verbose_name_plural': 'Lease area attachments',
            },
        ),
        migrations.RemoveField(
            model_name='leasearea',
            name='constructability_report_geotechnical_number',
        ),
        migrations.RemoveField(
            model_name='leasearea',
            name='polluted_land_matti_report_number',
        ),
        migrations.AddField(
            model_name='leaseareaattachment',
            name='lease_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='leasing.LeaseArea'),
        ),
        migrations.AddField(
            model_name='leaseareaattachment',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
    ]
