# Generated by Django 3.2.13 on 2022-08-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0050_customdetailedplan_usagedistribution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customdetailedplan",
            name="deleted",
        ),
    ]
