# Generated by Django 2.1.7 on 2019-02-28 13:06

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0051_add_lease_area_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseholdTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('institution_identifier', models.CharField(max_length=127, verbose_name='Institution identifier')),
                ('decision_date', models.DateField(verbose_name='Decision date')),
            ],
            options={
                'verbose_name': 'Leasehold transfer',
                'verbose_name_plural': 'Leasehold transfers',
            },
        ),
        migrations.CreateModel(
            name='LeaseholdTransferImportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('file_name', models.CharField(max_length=255, verbose_name='File name')),
            ],
            options={
                'verbose_name': 'Leasehold transfer import log',
                'verbose_name_plural': 'Leasehold transfer import logs',
            },
        ),
        migrations.CreateModel(
            name='LeaseholdTransferParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', enumfields.fields.EnumField(enum=leasing.enums.LeaseholdTransferPartyType, max_length=10)),
                ('business_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Business ID')),
                ('national_identification_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='National identification number')),
                ('share_numerator', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numerator')),
                ('share_denominator', models.PositiveIntegerField(blank=True, null=True, verbose_name='Denominator')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='leasing.LeaseholdTransfer', verbose_name='Leasehold transfer')),
            ],
            options={
                'verbose_name': 'Leasehold transfer party',
                'verbose_name_plural': 'Leasehold transfer parties',
                'ordering': ('-type',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaseholdTransferProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=127, verbose_name='Identifier')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='leasing.LeaseholdTransfer', verbose_name='Leasehold transfer')),
            ],
            options={
                'verbose_name': 'Leasehold transfer property',
                'verbose_name_plural': 'Leasehold transfer properties',
            },
        ),
    ]
