# Generated by Django 3.2.13 on 2022-09-28 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0051_remove_customdetailedplan_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customdetailedplan",
            name="section_area",
        ),
        migrations.AddField(
            model_name="customdetailedplan",
            name="address",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customdetailedplan",
            name="preconstruction_estimated_construction_readiness_moment",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Preconstruction estimated construction readiness",
            ),
        ),
        migrations.AddField(
            model_name="customdetailedplan",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leasing.planunittype",
            ),
        ),
        migrations.AlterField(
            model_name="customdetailedplan",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leasing.planunitstate",
            ),
        ),
        migrations.AlterField(
            model_name="usagedistribution",
            name="distribution",
            field=models.CharField(max_length=255),
        ),
    ]
