# Generated by Django 3.2.13 on 2022-10-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0052_update_customdetailedplan_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leasebasisofrent",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=10,
                null=True,
                verbose_name="Discount percentage",
            ),
        ),
    ]
