# Generated by Django 2.1.7 on 2019-03-01 12:24

from django.db import migrations
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0052_add_leasehold_transfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisiontype',
            name='kind',
            field=enumfields.fields.EnumField(blank=True, enum=leasing.enums.DecisionTypeKind, max_length=30, null=True, verbose_name='Decision type kind'),
        ),
    ]
