# Generated by Django 3.2.13 on 2022-10-31 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "leasing",
            "0053_add_decimal_places_to_lease_basis_of_rent_discount_percentage",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contractrent",
            name="index",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.index",
                verbose_name="Index",
            ),
        ),
    ]
