# Generated by Django 3.2.13 on 2023-02-13 08:46

from django.db import migrations

# Mark leases that have "application" as their state as deleted and change the state
# to "lease" because "application" state will be deleted. The deleted at time is kept as
# is in already deleted leases. Adds a note to the lease note to make it possible to
# reverse the change.
REMOVE_APPLICATION_SQL = """
UPDATE leasing_lease
SET state = 'lease',
    note =
    CASE WHEN deleted IS NOT NULL THEN
        CONCAT(note, '!!! state changed to "lease" by the 0055_remove_application_leases migration !!!')
    ELSE
        CONCAT(note, '!!! deleted and state changed to "lease" by the 0055_remove_application_leases migration !!!')
    END,
    deleted = CASE WHEN deleted IS NULL THEN NOW() ELSE deleted END
WHERE state = 'application';
"""

RESTORE_APPLICATION_STATE_SQL = """
UPDATE leasing_lease
SET state = 'application',
    note = REGEXP_REPLACE(
        note,
        '!!! .*state changed to "lease" by the 0055_remove_application_leases migration !!!',
        ''
    ),
    deleted = CASE WHEN POSITION('!!! deleted and ' in note) > 0 THEN
        NULL
    ELSE
        deleted
    END
WHERE note LIKE '%by the 0055_remove_application_leases migration%'
  AND state = 'lease'
  AND deleted IS NOT NULL;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0054_contractrent_index"),
    ]

    operations = [
        migrations.RunSQL(
            REMOVE_APPLICATION_SQL, reverse_sql=RESTORE_APPLICATION_STATE_SQL
        ),
    ]
