# Generated by Django 2.1.7 on 2019-03-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0054_add_fields_to_collection_court_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='is_readjustment_decision',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is readjustment decision'),
        ),
    ]
