# Generated by Django 2.1.7 on 2019-03-14 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0055_make_is_readjustment_decision_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areanote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='basisofrent',
            name='financing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.Financing', verbose_name='Form of financing'),
        ),
        migrations.AlterField(
            model_name='basisofrent',
            name='index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.Index', verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='basisofrent',
            name='management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.Management', verbose_name='Form of management'),
        ),
        migrations.AlterField(
            model_name='basisofrent',
            name='plot_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.BasisOfRentPlotType', verbose_name='Plot type'),
        ),
        migrations.AlterField(
            model_name='basisofrentdecision',
            name='decision_maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.DecisionMaker', verbose_name='Decision maker'),
        ),
        migrations.AlterField(
            model_name='basisofrentrate',
            name='build_permission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.BasisOfRentBuildPermissionType', verbose_name='Build permission type'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.CollateralType', verbose_name='Collateral type'),
        ),
        migrations.AlterField(
            model_name='collectioncourtdecision',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AlterField(
            model_name='collectionletter',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AlterField(
            model_name='collectionnote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.CommentTopic', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='constructabilitydescription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.Decision', verbose_name='Decision'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.ContractType', verbose_name='Contract type'),
        ),
        migrations.AlterField(
            model_name='contractchange',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.Decision', verbose_name='Decision'),
        ),
        migrations.AlterField(
            model_name='contractrent',
            name='intended_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.RentIntendedUse', verbose_name='Intended use'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='decision_maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.DecisionMaker', verbose_name='Decision maker'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='fixedinitialyearrent',
            name='intended_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.RentIntendedUse', verbose_name='Intended use'),
        ),
        migrations.AlterField(
            model_name='indexadjustedrent',
            name='intended_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.RentIntendedUse', verbose_name='Intended use'),
        ),
        migrations.AlterField(
            model_name='infilldevelopmentcompensation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='infilldevelopmentcompensationattachment',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AlterField(
            model_name='infilldevelopmentcompensationdecision',
            name='decision_maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.DecisionMaker', verbose_name='Decision maker'),
        ),
        migrations.AlterField(
            model_name='infilldevelopmentcompensationintendeduse',
            name='intended_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.IntendedUse', verbose_name='Intended use'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.Contact', verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='invoicerow',
            name='receivable_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.ReceivableType', verbose_name='Receivable type'),
        ),
        migrations.AlterField(
            model_name='invoicerow',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.Tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.District', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='financing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.Financing', verbose_name='Form of financing'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='hitas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.Hitas', verbose_name='Hitas'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='identifier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.LeaseIdentifier', verbose_name='Lease identifier'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='intended_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.IntendedUse', verbose_name='Intended use'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='lessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.Contact', verbose_name='Lessor'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.Management', verbose_name='Form of management'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.Municipality', verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='notice_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.NoticePeriod', verbose_name='Notice period'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='preparer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Preparer'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='regulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.Regulation', verbose_name='Form of regulation'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='special_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.SpecialProject', verbose_name='Special project'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='statistical_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.StatisticalUse', verbose_name='Statistical use'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='supportive_housing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.SupportiveHousing', verbose_name='Supportive housing'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.LeaseType', verbose_name='Lease type'),
        ),
        migrations.AlterField(
            model_name='leasearea',
            name='archived_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.Decision', verbose_name='Archived decision'),
        ),
        migrations.AlterField(
            model_name='leasearea',
            name='polluted_land_planner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='leaseareaattachment',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AlterField(
            model_name='leasebasisofrent',
            name='index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.Index', verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='leasebasisofrent',
            name='intended_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.RentIntendedUse', verbose_name='Intended use'),
        ),
        migrations.AlterField(
            model_name='leasebasisofrent',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Locked by'),
        ),
        migrations.AlterField(
            model_name='leasebasisofrent',
            name='plans_inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Plans inspected by'),
        ),
        migrations.AlterField(
            model_name='leaseidentifier',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.District', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='leaseidentifier',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.Municipality', verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='leaseidentifier',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.LeaseType', verbose_name='Lease type'),
        ),
        migrations.AlterField(
            model_name='planunit',
            name='plan_unit_intended_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.PlanUnitIntendedUse', verbose_name='Plan unit intended use'),
        ),
        migrations.AlterField(
            model_name='planunit',
            name='plan_unit_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.PlanUnitState', verbose_name='Plan unit state'),
        ),
        migrations.AlterField(
            model_name='planunit',
            name='plan_unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.PlanUnitType', verbose_name='Plan unit type'),
        ),
        migrations.AlterField(
            model_name='planunit',
            name='plot_division_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.PlotDivisionState', verbose_name='Plot division state'),
        ),
        migrations.AlterField(
            model_name='rentadjustment',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.Decision', verbose_name='Decision'),
        ),
        migrations.AlterField(
            model_name='rentadjustment',
            name='intended_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.RentIntendedUse', verbose_name='Intended use'),
        ),
        migrations.AlterField(
            model_name='uidata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
