# Generated by Django 2.1.7 on 2019-03-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0056_suppress_unused_reverse_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseareaaddress',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Is primary?'),
        ),
    ]
