# Generated by Django 2.1.7 on 2019-03-27 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0057_leaseareaaddress_is_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EqualizedRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payable amount')),
                ('equalized_payable_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Equalized payable amount')),
                ('equalization_factor', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Equalization factor')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equalized_rents', to='leasing.Rent', verbose_name='Rent')),
            ],
            options={
                'verbose_name': 'Equalized rent',
                'verbose_name_plural': 'Equalized rents',
            },
        ),
    ]
