# Generated by Django 2.1.7 on 2019-03-29 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0058_equalizedrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('billing_period_start_date', models.DateField(blank=True, null=True, verbose_name='Billing period start date')),
                ('billing_period_end_date', models.DateField(blank=True, null=True, verbose_name='Billing period end date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_notes', to='leasing.Lease', verbose_name='Lease')),
            ],
            options={
                'verbose_name': 'Invoice note',
                'verbose_name_plural': 'Invoice notes',
            },
        ),
    ]
