# Generated by Django 3.2.23 on 2024-03-13 14:49

from pathlib import Path
from django.db import migrations


def load_sql_file(name):
    file_path = Path(__file__).resolve().parent / name
    with open(file_path, encoding="utf-8") as file:
        return file.read()


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0059_alter_contact_language"),
    ]

    operations = [
        migrations.RunSQL(
            sql=load_sql_file(
                "0060_fix_paikkatietovipunen_vuokraalueet_remove_intended_use_requirement.sql"
            ),
            reverse_sql=load_sql_file(
                "0057_update_paikkatietovipunen_vuokraalueet_view.sql"
            ),
        ),
    ]
