# Generated by Django 3.2.9 on 2021-12-08 16:02

from django.db import migrations


def initialize_serviceunits(apps, schema_editor):
    ServiceUnit = apps.get_model("leasing", "ServiceUnit")  # noqa
    Contact = apps.get_model("leasing", "Contact")  # noqa
    Lease = apps.get_model("leasing", "Lease")  # noqa
    Invoice = apps.get_model("leasing", "Invoice")  # noqa

    service_unit = ServiceUnit.objects.create(
        id=1,
        name="Maaomaisuuden kehittäminen ja tontit",
        description="",
        laske_sender_id="ID340",
        laske_import_id="ID256",
        laske_sales_org="2800",
    )
    Contact.objects.all().update(service_unit=service_unit)
    Lease.objects.all().update(service_unit=service_unit)
    Invoice.objects.all().update(service_unit=service_unit)


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0059_add_service_unit_to_contact_invoice_and_lease"),
    ]

    operations = [
        migrations.RunPython(
            initialize_serviceunits, reverse_code=migrations.RunPython.noop
        ),
    ]
