# Generated by Django 2.2 on 2019-04-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0060_contact_new_language_from_django_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='arrangement_decision',
        ),
    ]
