# Generated by Django 2.2 on 2019-04-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0061_lease_remove_arrangement_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='interest_invoice_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interest_invoices', to='leasing.Invoice', verbose_name='Interest invoice for'),
        ),
    ]
