# Generated by Django 2.2 on 2019-04-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0062_invoice_interest_invoice_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='customer_number',
        ),
    ]
