# Generated by Django 2.2 on 2019-04-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0063_remove_contact_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='deed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deed date'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='other_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other type'),
        ),
    ]
