# Generated by Django 3.2.18 on 2023-09-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0063_serviceunitgroupmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceunit",
            name="contract_number_sequence_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Contract number sequence name",
            ),
        ),
        migrations.AddField(
            model_name="serviceunit",
            name="first_contract_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="First contract number"
            ),
        ),
    ]
