# Generated by Django 2.2 on 2019-04-24 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0064_add_fields_to_collateral'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1914', models.PositiveIntegerField(blank=True, null=True, verbose_name='Index 1914:1-6=100')),
                ('number_1938', models.PositiveIntegerField(blank=True, null=True, verbose_name='Index 1938:8-1939:7=100')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leasing.Index', verbose_name='Index')),
            ],
        ),
    ]
