# Generated by Django 2.2.1 on 2019-05-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0065_legacyindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='regulated',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Regulated'),
        ),
    ]
