# Generated by Django 2.2.1 on 2019-05-06 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import leasing.models.inspection


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leasing', '0066_make_lease_regulated_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Time modified')),
                ('file', models.FileField(upload_to=leasing.models.inspection.get_inspection_attachment_file_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Time uploaded')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='leasing.Inspection')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Uploader')),
            ],
            options={
                'verbose_name': 'Inspection attachment',
                'verbose_name_plural': 'Inspection attachments',
            },
        ),
    ]
