# Generated by Django 3.2.23 on 2023-12-06 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0069_receivabletype_service_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceunit",
            name="default_receivable_type_collateral",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Receivable type which should be used when creating collateral "
                    "invoices. On SAP export, the profit center is filled from this "
                    "receivable type's sap_order_item_number."
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.receivabletype",
                verbose_name="Default receivable type (collateral)",
            ),
        ),
        migrations.AddField(
            model_name="serviceunit",
            name="default_receivable_type_rent",
            field=models.ForeignKey(
                blank=True,
                help_text="Receivable type used when creating rent invoices",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.receivabletype",
                verbose_name="Default receivable type (rent)",
            ),
        ),
    ]
