# Generated by Django 2.2.1 on 2019-05-15 10:31

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0069_add_subvention_to_rent_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasebasisofrent',
            name='subvention_base_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subvention base percent'),
        ),
        migrations.AddField(
            model_name='leasebasisofrent',
            name='subvention_graduated_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Graduated subvention percent'),
        ),
        migrations.AddField(
            model_name='leasebasisofrent',
            name='subvention_type',
            field=enumfields.fields.EnumField(blank=True, enum=leasing.enums.SubventionType, max_length=30, null=True, verbose_name='Subvention type'),
        ),
        migrations.CreateModel(
            name='LeaseBasisOfRentTemporarySubvention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('subvention_percent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subvention percent')),
                ('lease_basis_of_rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_subventions', to='leasing.LeaseBasisOfRent', verbose_name='Lease basis of rent')),
            ],
            options={
                'verbose_name': 'Temporary subvention',
                'verbose_name_plural': 'Temporary subventions',
            },
        ),
        migrations.CreateModel(
            name='LeaseBasisOfRentManagementSubvention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subvention_percent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subvention percent')),
                ('lease_basis_of_rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_subventions', to='leasing.LeaseBasisOfRent', verbose_name='Lease basis of rent')),
                ('management', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leasing.Management', verbose_name='Form of management')),
            ],
            options={
                'verbose_name': 'Management subvention',
                'verbose_name_plural': 'Management subventions',
            },
        ),
    ]
