# Generated by Django 3.2.23 on 2023-12-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0070_add_default_receivable_type_fields_to_service_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="internal_order",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Internal order"
            ),
        ),
    ]
