# Generated by Django 4.2.11 on 2024-05-15 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0071_lease_internal_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vat",
            name="percent",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Percent",
            ),
        ),
    ]
