# Generated by Django 4.2.13 on 2024-06-07 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0072_alter_vat_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="intendeduse",
            name="service_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leasing.serviceunit",
            ),
        ),
    ]
