# Generated by Django 2.2.6 on 2019-10-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0073_management_subvention_changes'),
        ('leasing', '0073_invoicerow_intended_use'),
    ]

    operations = [
    ]
