# Generated by Django 4.2.14 on 2024-09-10 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0073_intendeduse_service_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="OldDwellingsInHousingCompaniesPriceIndex",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Index code"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Index name")),
                ("comment", models.TextField(blank=True, verbose_name="Region")),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Data source"
                    ),
                ),
                (
                    "source_table_updated",
                    models.DateTimeField(
                        null=True, verbose_name="Source table updated"
                    ),
                ),
                (
                    "source_table_label",
                    models.TextField(blank=True, verbose_name="Source table label"),
                ),
                (
                    "url",
                    models.CharField(max_length=255, verbose_name="API endpoint URL"),
                ),
            ],
            options={
                "verbose_name": "price index of old dwellings in housing companies",
                "verbose_name_plural": "price indexes of old dwellings in housing companies",
            },
        ),
        migrations.CreateModel(
            name="IndexNumberYearly",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "number",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=8,
                        null=True,
                        verbose_name="Index number",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Year")),
                (
                    "region",
                    models.CharField(blank=True, max_length=255, verbose_name="Region"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comment")),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="numbers",
                        to="leasing.olddwellingsinhousingcompaniespriceindex",
                        verbose_name="Index",
                    ),
                ),
            ],
            options={
                "verbose_name": "index number",
                "verbose_name_plural": "index numbers",
                "ordering": ("-index", "-year"),
            },
        ),
        migrations.AddConstraint(
            model_name="indexnumberyearly",
            constraint=models.UniqueConstraint(
                fields=("index", "year"), name="unique_price_index_number"
            ),
        ),
    ]
