# Generated by Django 4.2.14 on 2024-09-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0075_olddwellingsinhousingcompaniespriceindex_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceunit",
            name="abbreviation",
            field=models.CharField(
                default="-", max_length=15, verbose_name="Abbreviation"
            ),
            preserve_default=False,
        ),
    ]
