# Generated by Django 4.2.14 on 2024-10-23 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "leasing",
            "0076_paikkatietovipunen_vuokraalueet_view_vuokraustunnus_and_tyypin_tunnus",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rent",
            name="override_receivable_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.receivabletype",
                verbose_name="Override receivable type",
            ),
        ),
    ]
