# Generated by Django 4.2.14 on 2024-10-31 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0077_paikkatietovipunen_vuokraalueet_add_kami_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["type", "name", "last_name", "first_name"],
                "permissions": [
                    (
                        "view_contact_contacts_active_leases",
                        "Can view contacts active leases",
                    )
                ],
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
    ]
