# Generated by Django 4.2.14 on 2024-10-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0077_paikkatietovipunen_vuokraalueet_add_kami_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="intendeduse",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
