# Generated by Django 4.2.16 on 2024-11-21 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0080_alter_contact_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexnumberyearly",
            name="number",
        ),
        migrations.AddField(
            model_name="indexnumberyearly",
            name="point_figure",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=8,
                null=True,
                verbose_name="Index point figure",
            ),
        ),
        migrations.AddField(
            model_name="rent",
            name="old_dwellings_in_housing_companies_price_index",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.olddwellingsinhousingcompaniespriceindex",
                verbose_name="Old dwellings in housing companies price index",
            ),
        ),
        migrations.AddField(
            model_name="rent",
            name="start_price_index_point_figure",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=8,
                null=True,
                verbose_name="Start price index point figure",
            ),
        ),
    ]
