# Generated by Django 4.2.14 on 2024-11-15 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0080_alter_contact_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="rent",
            name="old_dwellings_in_housing_companies_price_index",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.olddwellingsinhousingcompaniespriceindex",
                verbose_name="Old dwellings in housing companies price index",
            ),
        ),
    ]
