# Generated by Django 4.2.14 on 2024-11-12 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0080_alter_contact_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rent",
            name="override_receivable_type",
        ),
        migrations.AddField(
            model_name="contractrent",
            name="override_receivable_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.receivabletype",
                verbose_name="Override receivable type",
            ),
        ),
    ]
