# Generated by Django 4.2.16 on 2024-11-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0081_rent_old_dwellings_in_housing_companies_price_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="rent",
            name="start_price_index",
            field=models.DecimalField(
                decimal_places=1, max_digits=8, null=True, verbose_name="Index number"
            ),
        ),
    ]
