# Generated by Django 4.2.16 on 2024-11-22 07:38

from django.db import migrations


class Migration(migrations.Migration):
    """
    The Seasonal Rent (kausivuokra) feature is not desired by the users anymore.
    In the past it has only been used in a single lease, which has already expired.
    """

    dependencies = [
        ("leasing", "0081_serviceunit_use_rent_override_receivable_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rent",
            name="seasonal_end_day",
        ),
        migrations.RemoveField(
            model_name="rent",
            name="seasonal_end_month",
        ),
        migrations.RemoveField(
            model_name="rent",
            name="seasonal_start_day",
        ),
        migrations.RemoveField(
            model_name="rent",
            name="seasonal_start_month",
        ),
    ]
