# Generated by Django 4.2.16 on 2024-11-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0082_remove_rent_seasonal_end_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexPointFigureYearly",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=1, max_digits=8, null=True, verbose_name="Value"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Year")),
                (
                    "region",
                    models.CharField(blank=True, max_length=255, verbose_name="Region"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comment")),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="point_figures",
                        to="leasing.olddwellingsinhousingcompaniespriceindex",
                        verbose_name="Index",
                    ),
                ),
            ],
            options={
                "verbose_name": "index number",
                "verbose_name_plural": "index numbers",
                "ordering": ("-index", "-year"),
            },
        ),
        migrations.AddField(
            model_name="rent",
            name="old_dwellings_in_housing_companies_price_index",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.olddwellingsinhousingcompaniespriceindex",
                verbose_name="Old dwellings in housing companies price index",
            ),
        ),
        migrations.AddField(
            model_name="rent",
            name="start_price_index_point_figure",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=8,
                null=True,
                verbose_name="Start price index point figure",
            ),
        ),
        migrations.DeleteModel(
            name="IndexNumberYearly",
        ),
        migrations.AddConstraint(
            model_name="indexpointfigureyearly",
            constraint=models.UniqueConstraint(
                fields=("index", "year"), name="unique_price_index_number"
            ),
        ),
    ]
