# Generated by Django 4.2.16 on 2024-11-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0082_rent_start_price_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexnumberyearly",
            name="number",
        ),
        migrations.AddField(
            model_name="indexnumberyearly",
            name="point_figure",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=8,
                null=True,
                verbose_name="Index point figure",
            ),
        ),
        migrations.AlterField(
            model_name="rent",
            name="start_price_index",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=8,
                null=True,
                verbose_name="Start price index point figure",
            ),
        ),
    ]
