# Generated by Django 4.2.16 on 2024-12-09 11:27

from django.db import migrations
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0083_indexpointfigureyearly_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rent",
            name="old_dwellings_in_housing_companies_price_index_type",
            field=enumfields.fields.EnumField(
                blank=True,
                enum=leasing.enums.OldDwellingsInHousingCompaniesPriceIndexType,
                max_length=20,
                null=True,
                verbose_name="Old dwellings in housing companies price index type",
            ),
        ),
    ]
