# Generated by Django 4.2.16 on 2024-12-10 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0084_rent_old_dwellings_in_housing_companies_price_index_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="leasetype",
            name="sap_project_number",
            field=models.CharField(
                blank=True,
                help_text="This field takes priority over 'SAP order item number' if both are set.",
                max_length=255,
                null=True,
                verbose_name="SAP project number",
            ),
        ),
        migrations.AddField(
            model_name="receivabletype",
            name="sap_project_number",
            field=models.CharField(
                blank=True,
                help_text="This field takes priority over 'SAP order item number' if both are set.",
                max_length=255,
                null=True,
                verbose_name="SAP project number",
            ),
        ),
        migrations.AlterField(
            model_name="leasetype",
            name="sap_order_item_number",
            field=models.CharField(
                blank=True,
                help_text="If 'SAP project number' is set, it will be used instead of this value.",
                max_length=255,
                null=True,
                verbose_name="SAP order item number",
            ),
        ),
        migrations.AlterField(
            model_name="receivabletype",
            name="sap_order_item_number",
            field=models.CharField(
                blank=True,
                help_text="If 'SAP project number' is set, it will be used instead of this value.",
                max_length=255,
                null=True,
                verbose_name="SAP order item number",
            ),
        ),
        migrations.AlterField(
            model_name="serviceunit",
            name="default_receivable_type_collateral",
            field=models.ForeignKey(
                blank=True,
                help_text="Receivable type which should be used when creating collateral invoices. On SAP export, the profit center is filled from this receivable type's sap_project_number or sap_order_item_number.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.receivabletype",
                verbose_name="Default receivable type (collateral)",
            ),
        ),
    ]
