# Generated by Django 4.2.16 on 2024-12-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0085_leasetype_sap_project_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leasearea",
            options={
                "ordering": [
                    models.OrderBy(models.F("archived_at"), nulls_first=True),
                    "id",
                ],
                "verbose_name": "Lease area",
                "verbose_name_plural": "Lease areas",
            },
        ),
        migrations.AlterModelOptions(
            name="leaseareaaddress",
            options={
                "ordering": ["-is_primary", "id"],
                "verbose_name": "Lease area address",
                "verbose_name_plural": "Lease area addresses",
            },
        ),
    ]
