# Generated by Django 4.2.16 on 2025-01-02 14:32

from pathlib import Path
from django.db import migrations


def load_sql_file(name):
    file_path = Path(__file__).resolve().parent / name
    with open(file_path, encoding="utf-8") as file:
        return file.read()


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0086_add_ordering_to_areas_and_addresses"),
    ]

    operations = [
        migrations.RunSQL(
            sql=load_sql_file("./0087_permissions_view.sql"),
            reverse_sql="DROP VIEW IF EXISTS public.view_permissions;",
        ),
    ]
