# Generated by Django 4.2.16 on 2025-01-14 07:42

import django.core.files.storage
from django.db import migrations
import file_operations.private_files


def get_collection_court_decision_file_upload_to(instance, filename):
    return "/".join(["court_decisions", str(instance.lease.id), filename])


def get_collection_letter_file_upload_to(instance, filename):
    return "/".join(["collection_letters", str(instance.lease.id), filename])


def get_infill_development_compensation_attachment_file_upload_to(instance, filename):
    return "/".join(
        [
            "idc_attachments",
            str(instance.infill_development_compensation_lease.id),
            filename,
        ]
    )


def get_inspection_attachment_file_upload_to(instance, filename):
    return "/".join(["inspection_attachments", str(instance.inspection.id), filename])


def get_land_use_agreement_attachment_file_upload_to(instance, filename):
    return "/".join(["lease_area_attachments", str(instance.lease_area.id), filename])


def get_leasearea_attachment_file_upload_to(instance, filename):
    return "/".join(["lease_area_attachments", str(instance.lease_area.id), filename])


class Migration(migrations.Migration):

    dependencies = [
        (
            "leasing",
            "0088_remove_rent_old_dwellings_in_housing_companies_price_index_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectioncourtdecision",
            name="file",
            field=file_operations.private_files.PrivateFileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/attachments/", location="attachments"
                ),
                upload_to=get_collection_court_decision_file_upload_to,
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="collectionletter",
            name="file",
            field=file_operations.private_files.PrivateFileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/attachments/", location="attachments"
                ),
                upload_to=get_collection_letter_file_upload_to,
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="collectionlettertemplate",
            name="file",
            field=file_operations.private_files.PrivateFileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/attachments/", location="attachments"
                ),
                upload_to="collection_letter_templates/",
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="infilldevelopmentcompensationattachment",
            name="file",
            field=file_operations.private_files.PrivateFileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/attachments/", location="attachments"
                ),
                upload_to=get_infill_development_compensation_attachment_file_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="inspectionattachment",
            name="file",
            field=file_operations.private_files.PrivateFileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/attachments/", location="attachments"
                ),
                upload_to=get_inspection_attachment_file_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementattachment",
            name="file",
            field=file_operations.private_files.PrivateFileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/attachments/", location="attachments"
                ),
                upload_to=get_land_use_agreement_attachment_file_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="leaseareaattachment",
            name="file",
            field=file_operations.private_files.PrivateFileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/attachments/", location="attachments"
                ),
                upload_to=get_leasearea_attachment_file_upload_to,
            ),
        ),
    ]
