# Generated by Django 4.2.16 on 2025-01-14 07:42

import django.core.files.storage
from django.db import migrations
import leasing.models.debt_collection
import leasing.models.infill_development_compensation
import leasing.models.inspection
import leasing.models.land_area
import leasing.models.land_use_agreement
import utils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "leasing",
            "0088_remove_rent_old_dwellings_in_housing_companies_price_index_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectioncourtdecision",
            name="file",
            field=utils.models.fields.PrivateFileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/attachments/", location="attachments"
                ),
                upload_to=leasing.models.debt_collection.get_collection_court_decision_file_upload_to,
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="collectionletter",
            name="file",
            field=utils.models.fields.PrivateFileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/attachments/", location="attachments"
                ),
                upload_to=leasing.models.debt_collection.get_collection_letter_file_upload_to,
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="collectionlettertemplate",
            name="file",
            field=utils.models.fields.PrivateFileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/attachments/", location="attachments"
                ),
                upload_to="collection_letter_templates/",
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="infilldevelopmentcompensationattachment",
            name="file",
            field=utils.models.fields.PrivateFileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/attachments/", location="attachments"
                ),
                upload_to=leasing.models.infill_development_compensation.get_attachment_file_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="inspectionattachment",
            name="file",
            field=utils.models.fields.PrivateFileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/attachments/", location="attachments"
                ),
                upload_to=leasing.models.inspection.get_inspection_attachment_file_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="landuseagreementattachment",
            name="file",
            field=utils.models.fields.PrivateFileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/attachments/", location="attachments"
                ),
                upload_to=leasing.models.land_use_agreement.get_attachment_file_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="leaseareaattachment",
            name="file",
            field=utils.models.fields.PrivateFileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/attachments/", location="attachments"
                ),
                upload_to=leasing.models.land_area.get_attachment_file_upload_to,
            ),
        ),
    ]
