# Generated by Django 4.2.19 on 2025-02-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0089_private_filefield"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leasearea",
            options={
                "ordering": [
                    models.OrderBy(models.F("archived_at"), nulls_first=True),
                    "id",
                ],
                "permissions": [
                    ("export_api_lease_area", "Can access export API lease area")
                ],
                "verbose_name": "Lease area",
                "verbose_name_plural": "Lease areas",
            },
        ),
    ]
