# Generated by Django 4.2.19 on 2025-03-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0090_alter_leasearea_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="leasebasisofrent",
            name="initial_year_rent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Initial year rent",
            ),
        ),
    ]
