# Generated by Django 4.2.19 on 2025-03-17 09:28

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0090_alter_leasearea_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicRentAdjustment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "adjustment_type",
                    enumfields.fields.EnumField(
                        enum=leasing.enums.PeriodicRentAdjustmentType,
                        max_length=20,
                        verbose_name="Periodic rent adjustment type",
                    ),
                ),
                (
                    "starting_point_figure_value",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=8,
                        verbose_name="Price index point figure value at the start of the rent",
                    ),
                ),
                (
                    "starting_point_figure_year",
                    models.PositiveSmallIntegerField(
                        verbose_name="Year of the starting point figure"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="indexpointfigureyearly",
            options={
                "ordering": ("-index", "-year"),
                "verbose_name": "index point figure",
                "verbose_name_plural": "index point figures",
            },
        ),
        migrations.RemoveConstraint(
            model_name="indexpointfigureyearly",
            name="unique_price_index_number",
        ),
        migrations.RemoveField(
            model_name="rent",
            name="old_dwellings_in_housing_companies_price_index",
        ),
        migrations.RemoveField(
            model_name="rent",
            name="periodic_rent_adjustment_type",
        ),
        migrations.RemoveField(
            model_name="rent",
            name="start_price_index_point_figure",
        ),
        migrations.AddConstraint(
            model_name="indexpointfigureyearly",
            constraint=models.UniqueConstraint(
                fields=("index", "year"), name="unique_price_index_point_figure_yearly"
            ),
        ),
        migrations.AddField(
            model_name="periodicrentadjustment",
            name="price_index",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.olddwellingsinhousingcompaniespriceindex",
                verbose_name="Price index for periodic rent adjustment",
            ),
        ),
        migrations.AddField(
            model_name="rent",
            name="periodic_rent_adjustment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.periodicrentadjustment",
                verbose_name="Periodic rent adjustment",
            ),
        ),
    ]
