# Generated by Django 4.2.19 on 2025-03-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0091_vipunenmaplayer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vipunenmaplayer",
            old_name="intended_use",
            new_name="filter_by_intended_use",
        ),
        migrations.RenameField(
            model_name="vipunenmaplayer",
            old_name="lease_type",
            new_name="filter_by_lease_type",
        ),
        migrations.AddField(
            model_name="vipunenmaplayer",
            name="filter_by_service_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="map_layers",
                to="leasing.serviceunit",
            ),
        ),
    ]
