# Generated by Django 4.2.19 on 2025-03-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "leasing",
            "0092_rename_intended_use_vipunenmaplayer_filter_by_intended_use_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vipunenmaplayer",
            name="filter_by_intended_use",
        ),
        migrations.RemoveField(
            model_name="vipunenmaplayer",
            name="filter_by_lease_type",
        ),
        migrations.AddField(
            model_name="vipunenmaplayer",
            name="filter_by_intended_use",
            field=models.ManyToManyField(
                blank=True, related_name="map_layers", to="leasing.intendeduse"
            ),
        ),
        migrations.AddField(
            model_name="vipunenmaplayer",
            name="filter_by_lease_type",
            field=models.ManyToManyField(
                blank=True, related_name="map_layers", to="leasing.leasetype"
            ),
        ),
    ]
