# Generated by Django 4.2.19 on 2025-03-19 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0094_periodic_rent_adjustment_year_and_terminology"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationMetadata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_received_at",
                    models.DateField(
                        blank=True,
                        help_text="The date the application was received.",
                        null=True,
                        verbose_name="Application received at",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lease",
            name="application_metadata",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="leasing.applicationmetadata",
            ),
        ),
    ]
