# Generated by Django 4.2.19 on 2025-03-25 08:46

from django.db import migrations, models
import leasing.validators


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0095_applicationmetadata_lease_application_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceunit",
            name="hex_color",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                validators=[leasing.validators.HexColorValidator()],
            ),
        ),
    ]
