# Generated by Django 4.2.19 on 2025-03-26 12:47

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0096_serviceunit_hex_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportStorage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report_data",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                ("report_type", models.CharField(max_length=255)),
                ("input_data", models.JSONField(null=True)),
            ],
            options={
                "permissions": [
                    (
                        "export_api_lease_statistic_report",
                        "Can access export API for lease statistics report",
                    )
                ],
            },
        ),
    ]
