# Generated by Django 4.2.20 on 2025-04-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0097_reportstorage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leasebasisofrent",
            name="subvention_graduated_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Subvention graduated percent",
            ),
        ),
    ]
