# Generated by Django 4.2.20 on 2025-06-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0100_contract_executor_contractchange_executor"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="invoicing_enabled_at",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Invoicing enabled at?"
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="rent_info_completed_at",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Rent info completed at?"
            ),
        ),
    ]
