# Generated by Django 4.2.20 on 2025-06-11 06:09

from django.db import migrations
from django.db.models import F, QuerySet


def convert_boolean_to_datetime(apps, schema_editor):
    Lease = apps.get_model("leasing", "Lease")  # noqa: N806

    leases_with_is_invoicing_enabled: QuerySet = Lease.objects.filter(
        is_invoicing_enabled=True
    )
    leases_with_is_invoicing_enabled.update(invoicing_enabled_at=F("created_at"))

    leases_with_is_rent_info_complete: QuerySet = Lease.objects.filter(
        is_rent_info_complete=True
    )
    leases_with_is_rent_info_complete.update(rent_info_completed_at=F("created_at"))


def reverse_datetime_to_boolean(apps, schema_editor):
    Lease = apps.get_model("leasing", "Lease")  # noqa: N806

    leases_with_invoicing_enabled_at: QuerySet = Lease.objects.filter(
        invoicing_enabled_at__isnull=False
    )
    leases_with_invoicing_enabled_at.update(is_invoicing_enabled=True)

    leases_with_rent_info_completed_at: QuerySet = Lease.objects.filter(
        rent_info_completed_at__isnull=False
    )
    leases_with_rent_info_completed_at.update(is_rent_info_complete=True)


class Migration(migrations.Migration):
    """
    Migration to convert boolean fields is_invoicing_enabled and is_rent_info_complete
    to datetime fields invoicing_enabled_at and rent_info_completed_at.
    Gets datetime from Leases `created_at` field for those that have invoicing_enabled or rent_info_complete.
    """

    dependencies = [
        ("leasing", "0101_add_lease_invoicing_enabled_at_and_more"),
    ]

    operations = [  # Migrate data from existing fields to new fields
        migrations.RunPython(
            convert_boolean_to_datetime, reverse_code=reverse_datetime_to_boolean
        ),
    ]
