# Generated by Django 4.2.20 on 2025-06-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0102_data_migration_invoicing_enabled_at_and_more_20250611_0909"),
    ]

    operations = [  # Remove previous boolean fields
        migrations.RemoveField(
            model_name="lease",
            name="is_invoicing_enabled",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="is_rent_info_complete",
        ),
    ]
