# Generated by Django 4.2.20 on 2025-06-13 07:44

from django.db import migrations


class Migration(migrations.Migration):
    """Adds a permission to access the export API for expired leases."""

    dependencies = [
        ("leasing", "0103_remove_leasing_is_invoicing_enabled_and_more_20250611_0909"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lease",
            options={
                "permissions": [
                    ("delete_nonempty_lease", "Can delete non-empty Lease"),
                    (
                        "export_api_expired_lease",
                        "Can access export API expired leases",
                    ),
                ],
                "verbose_name": "Lease",
                "verbose_name_plural": "Leases",
            },
        ),
    ]
