# Generated by Django 4.2.20 on 2025-06-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0104_export_api_expired_leases"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportstorage",
            options={
                "permissions": [
                    (
                        "export_api_lease_statistic_report",
                        "Can access export API for lease statistics report",
                    ),
                    (
                        "export_api_lease_processing_time_report",
                        "Can access export API for lease processing time report",
                    ),
                ]
            },
        ),
    ]
