# Generated by Django 4.2.20 on 2025-07-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0105_alter_reportstorage_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BankHoliday",
        ),
    ]
