# Generated by Django 4.2.23 on 2025-08-04 10:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0106_delete_bankholiday"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaseAreaDraft",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Time archived"
                    ),
                ),
                (
                    "archived_note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Archived note"
                    ),
                ),
                (
                    "identifier",
                    models.CharField(max_length=255, verbose_name="Identifier"),
                ),
                (
                    "area",
                    models.PositiveIntegerField(verbose_name="Area in square meters"),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Geometry"
                    ),
                ),
                (
                    "location",
                    enumfields.fields.EnumField(
                        enum=leasing.enums.LocationType,
                        max_length=30,
                        verbose_name="Location",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Address"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Postal code",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="City"
                    ),
                ),
                (
                    "lease",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lease_area_draft",
                        to="leasing.lease",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lease area draft",
                "verbose_name_plural": "Lease area drafts",
            },
        ),
    ]
