# Generated by Django 4.2.23 on 2025-08-05 08:32

from django.db import migrations, models
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0107_leaseareadraft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaseareadraft",
            name="area",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Area in square meters"
            ),
        ),
        migrations.AlterField(
            model_name="leaseareadraft",
            name="identifier",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Identifier"
            ),
        ),
        migrations.AlterField(
            model_name="leaseareadraft",
            name="location",
            field=enumfields.fields.EnumField(
                blank=True,
                enum=leasing.enums.LocationType,
                max_length=30,
                null=True,
                verbose_name="Location",
            ),
        ),
    ]
