# Generated by Django 4.2.23 on 2025-08-08 07:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0108_alter_leaseareadraft_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leasearea",
            name="draft_geometry",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326, verbose_name="Draft geometry"
            ),
        ),
    ]
