# Generated by Django 4.2.23 on 2025-09-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0109_leasearea_draft_geometry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LeaseAreaDraft",
        ),
    ]
