# Generated by Django 4.2.23 on 2025-09-01 13:04

from django.db import migrations
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0110_delete_leaseareadraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicerow",
            name="type",
            field=enumfields.fields.EnumField(
                enum=leasing.enums.InvoiceRowType,
                max_length=30,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
