# Generated by Django 4.2.23 on 2025-09-01 13:04
from django.utils.translation import pgettext_lazy

from enumfields import Enum
from django.db import migrations
import enumfields.fields


class InvoiceRowType(Enum):
    """
    In Finnish: Laskun rivin tyyppi

    Was moved into this migration after it was removed from the model itself, to
    avoid issues with environments that had already applied this migration
    before.
    """

    CHARGE = "charge"
    CREDIT = "credit"
    ROUNDING = "rounding"

    class Labels:
        CHARGE = pgettext_lazy("Invoice row type", "Charge")
        CREDIT = pgettext_lazy("Invoice row type", "Credit")
        ROUNDING = pgettext_lazy("Invoice row type", "Rounding")


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0110_delete_leaseareadraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicerow",
            name="type",
            field=enumfields.fields.EnumField(
                enum=InvoiceRowType,
                max_length=30,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
