# Generated by Django 4.2.23 on 2025-09-12 10:41

from django.db import migrations


class Migration(migrations.Migration):
    """Removes an enumfield that already applied to environments in previous
    migration."""

    dependencies = [
        ("leasing", "0111_invoicerow_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoicerow",
            name="type",
        ),
    ]
