# Generated by Django 4.2.23 on 2025-09-22 08:03

from pathlib import Path
from django.db import migrations


def load_sql_file(name):
    file_path = Path(__file__).resolve().parent / name
    with open(file_path, encoding="utf-8") as file:
        return file.read()


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0112_remove_invoicerow_type"),
    ]

    operations = [
        # Remove Vipunen database view and database role `kami`.
        migrations.RunSQL(
            sql=load_sql_file("./0113_remove_vipunen_view.sql"),
            reverse_sql=load_sql_file(
                "./0077_paikkatietovipunen_vuokraalueet_add_kami_permissions.sql"
            ),
        ),
    ]
