# Generated by Django 4.2.23 on 2025-10-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0114_remove_constance_tables"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="intendeduse",
            constraint=models.UniqueConstraint(
                fields=("name", "service_unit"),
                name="unique_intendeduse_name_serviceunit",
            ),
        ),
        migrations.AddConstraint(
            model_name="intendeduse",
            constraint=models.UniqueConstraint(
                fields=("name_fi", "service_unit"),
                name="unique_intendeduse_name_serviceunit-name_fi",
            ),
        ),
        migrations.AddConstraint(
            model_name="intendeduse",
            constraint=models.UniqueConstraint(
                fields=("name_sv", "service_unit"),
                name="unique_intendeduse_name_serviceunit-name_sv",
            ),
        ),
        migrations.AddConstraint(
            model_name="intendeduse",
            constraint=models.UniqueConstraint(
                fields=("name_en", "service_unit"),
                name="unique_intendeduse_name_serviceunit-name_en",
            ),
        ),
    ]
