# Generated by Django 4.2.23 on 2025-10-22 13:07

from django.db import migrations


class Migration(migrations.Migration):
    """This migration is not really for the Leasing app.
    It is intended to remove the data of `django-constance` package.
    No reverse SQL operation is provided, since that should be handled by the package itself,
    once it is added to INSTALLED_APPS again."""

    dependencies = [
        ("leasing", "0114_intendeduse_unique_intendeduse_name_serviceunit_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                BEGIN;
                DROP TABLE IF EXISTS constance_constance;
                DELETE FROM django_migrations WHERE app = 'constance';
                COMMIT;
            """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
