# Generated by Django 4.2.23 on 2025-11-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0115_intendeduse_unique_intendeduse_name_serviceunit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leasetype",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Is the Lease Type active?",
                verbose_name="Is active?",
            ),
        ),
    ]
