# Generated by Django 4.2.27 on 2026-01-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0117_serviceunit_is_application_received_at_mandatory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leasearea",
            name="draft_geometry",
        ),
    ]
