# Generated by Django 4.2.25 on 2026-01-21 08:35

from django.db import migrations
import enumfields.fields
import leasing.enums


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0119_remove_landuseagreementaddress_land_use_agreement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionnote",
            name="collection_stage",
            field=enumfields.fields.EnumField(
                blank=True,
                enum=leasing.enums.CollectionStage,
                max_length=50,
                null=True,
                verbose_name="Collection stage",
            ),
        ),
    ]
