# Generated by Django 5.2.15 on 2026-08-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "leasing",
            "0122_alter_helptext_for_serviceunit_use_rent_override_receivable_type",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionnote",
            name="entire_lease",
            field=models.BooleanField(default=False, verbose_name="Entire lease"),
        ),
        migrations.AddField(
            model_name="collectionnote",
            name="inspection_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Inspection date"
            ),
        ),
        migrations.AddField(
            model_name="collectionnote",
            name="invoices",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="leasing.invoice",
                verbose_name="Invoices",
            ),
        ),
        migrations.AddField(
            model_name="collectionnote",
            name="postpone_date",
            field=models.DateField(blank=True, null=True, verbose_name="Postpone date"),
        ),
        migrations.AddField(
            model_name="collectionnote",
            name="sent_date",
            field=models.DateField(blank=True, null=True, verbose_name="Sent date"),
        ),
    ]
