# Generated by Django 2.2.13 on 2021-09-03 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plotsearch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotsearchtarget",
            name="plan_unit",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leasing.PlanUnit",
            ),
        ),
    ]
