# Generated by Django 2.2.24 on 2021-10-27 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plotsearch", "0005_info_links_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotsearchtarget",
            name="plot_search",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plot_search_targets",
                to="plotsearch.PlotSearch",
            ),
        ),
    ]
