# Generated by Django 3.2.9 on 2021-11-11 11:04

from django.db import migrations
import enumfields.fields
import plotsearch.enums


class Migration(migrations.Migration):

    dependencies = [
        ("plotsearch", "0006_plot_search_target_rel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotsearch",
            name="search_class",
            field=enumfields.fields.EnumField(
                blank=True, enum=plotsearch.enums.SearchClass, max_length=30, null=True
            ),
        ),
    ]
