# Generated by Django 3.2.9 on 2021-12-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plotsearch", "0007_plotsearch_search_class"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plotsearchtype",
            options={
                "ordering": ["ordering", "name"],
                "verbose_name": "Plot search type",
                "verbose_name_plural": "Plot search types",
            },
        ),
        migrations.AddField(
            model_name="plotsearchsubtype",
            name="show_district",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plotsearchtype",
            name="ordering",
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
