# Generated by Django 3.2.10 on 2021-12-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plotsearch", "0009_add_ordering_field_plotsearchsubtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotsearchsubtype",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="plotsearchsubtype",
            name="name_fi",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="plotsearchsubtype",
            name="name_sv",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="plotsearchtype",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="plotsearchtype",
            name="name_fi",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="plotsearchtype",
            name="name_sv",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
    ]
