# Generated by Django 3.2.12 on 2022-02-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0014_add_create_and_open_fields_to_answer"),
        ("plotsearch", "0011_favourite_favouritetarget"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reserved", models.BooleanField(default=False)),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="forms.answer",
                    ),
                ),
                (
                    "plot_search_target",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="plotsearch.plotsearchtarget",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plotsearchtarget",
            name="answers",
            field=models.ManyToManyField(
                blank=True,
                related_name="targets",
                through="plotsearch.ApplicationStatus",
                to="forms.Answer",
            ),
        ),
    ]
