# Generated by Django 3.2.12 on 2022-04-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plotsearch", "0013_areasearch_intendedsubuse_intendeduse"),
    ]

    operations = [
        migrations.RemoveField(model_name="areasearch", name="description_project",),
        migrations.AddField(
            model_name="intendedsubuse",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="intendedsubuse",
            name="name_fi",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="intendedsubuse",
            name="name_sv",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="intendeduse",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="intendeduse",
            name="name_fi",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="intendeduse",
            name="name_sv",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
    ]
