# Generated by Django 3.2.13 on 2022-06-06 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import plotsearch.enums


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0017_add_entrysection_model_add_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plotsearch", "0014_add_translations_and_remove_project_description_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformationCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    enumfields.fields.EnumField(
                        enum=plotsearch.enums.InformationCheckName, max_length=30
                    ),
                ),
                (
                    "state",
                    enumfields.fields.EnumField(
                        default="not_checked",
                        enum=plotsearch.enums.InformationState,
                        max_length=30,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "entry_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="forms.entrysection",
                    ),
                ),
                (
                    "preparer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Preparer",
                    ),
                ),
            ],
        ),
    ]
