# Generated by Django 3.2.13 on 2022-09-05 10:45

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import enumfields.fields
import plotsearch.enums


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plotsearch", "0016_alter_informationcheck_entry_section"),
    ]

    operations = [
        migrations.RemoveField(model_name="plotsearch", name="preparer",),
        migrations.AddField(
            model_name="informationcheck",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Time created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="informationcheck",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Time modified"),
        ),
        migrations.AddField(
            model_name="plotsearch",
            name="preparers",
            field=models.ManyToManyField(
                blank=True,
                related_name="_plotsearch_plotsearch_preparers_+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Preparer",
            ),
        ),
        migrations.AddField(
            model_name="plotsearchstage",
            name="stage",
            field=enumfields.fields.EnumField(
                blank=True,
                default="in_preparation",
                enum=plotsearch.enums.SearchStage,
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plotsearchsubtype",
            name="target_selection",
            field=models.BooleanField(default=False),
        ),
    ]
