# Generated by Django 3.2.13 on 2023-01-09 10:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import plotsearch.enums
import plotsearch.models.plot_search


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0019_section_applicant_type"),
        (
            "leasing",
            "0053_add_decimal_places_to_lease_basis_of_rent_discount_percentage",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plotsearch", "0018_add_relation_to_custometailedplan"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingMemo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "meeting_memo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=plotsearch.models.plot_search.get_meeting_memo_file_upload_to,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProposedFinancingManagement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hitas",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="leasing.hitas",
                        verbose_name="Hitas",
                    ),
                ),
                (
                    "proposed_financing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="leasing.financing",
                        verbose_name="Form of financing",
                    ),
                ),
                (
                    "proposed_management",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="leasing.management",
                        verbose_name="Form of management",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TargetStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_of_rental_indicator",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "share_of_rental_denominator",
                    models.IntegerField(blank=True, null=True),
                ),
                ("reserved", models.BooleanField(default=False)),
                ("added_target_to_applicant", models.BooleanField(default=False)),
                ("counsel_date", models.DateTimeField(blank=True, null=True)),
                (
                    "decline_reason",
                    enumfields.fields.EnumField(
                        blank=True,
                        enum=plotsearch.enums.DeclineReason,
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "reservation_conditions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                ("arguments", models.TextField(blank=True, null=True)),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="forms.answer",
                    ),
                ),
                (
                    "plot_search_target",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="plotsearch.plotsearchtarget",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="proposedfinancingmanagement",
            name="target_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposed_managements",
                to="plotsearch.targetstatus",
            ),
        ),
        migrations.AddField(
            model_name="meetingmemo",
            name="target_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting_memos",
                to="plotsearch.targetstatus",
            ),
        ),
        migrations.AddField(
            model_name="meetingmemo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting_memos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="plotsearchtarget",
            name="answers",
            field=models.ManyToManyField(
                blank=True,
                related_name="targets",
                through="plotsearch.TargetStatus",
                to="forms.Answer",
            ),
        ),
        migrations.DeleteModel(name="ApplicationStatus",),
    ]
