# Generated by Django 3.2.13 on 2023-01-09 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "leasing",
            "0053_add_decimal_places_to_lease_basis_of_rent_discount_percentage",
        ),
        ("plotsearch", "0019_modify_targetstatus_related_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plotsearch",
            name="targets",
        ),
        migrations.AddField(
            model_name="plotsearchtarget",
            name="custom_detailed_plan",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leasing.customdetailedplan",
            ),
        ),
        migrations.AlterField(
            model_name="plotsearchtarget",
            name="plan_unit",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leasing.planunit",
            ),
        ),
    ]
