# Generated by Django 3.2.13 on 2023-02-23 10:32

from django.db import migrations, models
from django.utils import timezone

import plotsearch.models.plot_search


def add_application_identifier(apps, schema_editor):
    TargetStatus = apps.get_model("plotsearch", "TargetStatus")

    year = str(timezone.now().year)[2:4]

    beginning_str = "MVJ-{}".format(year)
    identifier = 1

    for target_status in TargetStatus.objects.all():
        target_status.application_identifier = "{}-{:05d}}".format(
            beginning_str, identifier
        )
        identifier += 1
        target_status.save()


class Migration(migrations.Migration):

    dependencies = [
        ("plotsearch", "0020_add_relation_to_customdetailedplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetstatus",
            name="application_identifier",
            field=models.CharField(max_length=255, unique=True,),
        ),
        migrations.RunPython(add_application_identifier),
        migrations.AlterField(
            model_name="targetstatus",
            name="application_identifier",
            field=models.CharField(
                default=plotsearch.models.plot_search.target_status_id_generator,
                max_length=255,
                unique=True,
            ),
        ),
    ]
