# Generated by Django 3.2.13 on 2023-04-26 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
from django.db.migrations import RunPython
from django.utils import timezone

import plotsearch.enums
import plotsearch.models.plot_search


def add_areasearch_identifier(apps, schema_editor):
    AreaSearch = apps.get_model("plotsearch", "AreaSearch")

    year = str(timezone.now().year)[2:4]

    beginning_str = "MVJ-{}".format(year)
    identifier = 1

    for area_search in AreaSearch.objects.all():
        area_search.identifier = "{}-{:05d}".format(beginning_str, identifier)
        identifier += 1
        area_search.save()


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0020_form_is_area_form"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plotsearch", "0021_targetstatus_application_identifier"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaSearchAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=plotsearch.models.plot_search.get_area_search_attachment_upload_to,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
            ],
            options={"ordering": ["name"], "abstract": False, },
        ),
        migrations.AddField(
            model_name="areasearch",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="areasearch",
            name="answer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="area_search",
                to="forms.answer",
            ),
        ),
        migrations.AddField(
            model_name="areasearch",
            name="district",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="areasearch",
            name="identifier",
            field=models.CharField(blank=True, null=True, max_length=255, unique=True),
        ),
        migrations.RunPython(add_areasearch_identifier, RunPython.noop),
        migrations.AlterField(
            model_name="areasearch",
            name="identifier",
            field=models.CharField(
                default=plotsearch.models.plot_search.areasearch_id_generator,
                max_length=255,
                blank=False,
                null=False,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="areasearch",
            name="lessor",
            field=enumfields.fields.EnumField(
                blank=True,
                default=None,
                enum=plotsearch.enums.AreaSearchLessor,
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="areasearch",
            name="preparer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Preparer",
            ),
        ),
        migrations.AddField(
            model_name="areasearch",
            name="received_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Time received",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="areasearch",
            name="state",
            field=enumfields.fields.EnumField(
                default="received",
                enum=plotsearch.enums.AreaSearchState,
                max_length=30,
                verbose_name="Area search state",
            ),
        ),
        migrations.AddField(
            model_name="areasearch",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="areasearch",
            name="form",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="area_searches",
                to="forms.form",
            ),
        ),
        migrations.AlterField(
            model_name="areasearch",
            name="intended_use",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plotsearch.intendeduse"
            ),
        ),
        migrations.DeleteModel(name="IntendedSubUse",),
        migrations.AddField(
            model_name="areasearchattachment",
            name="area_search",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="area_search_attachments",
                to="plotsearch.areasearch",
            ),
        ),
        migrations.AddField(
            model_name="areasearchattachment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
