# Generated by Django 3.2.13 on 2023-03-29 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0056_attach_usage_distribution_to_plan_unit"),
        ("plotsearch", "0022_modify_areasearch_related_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotsearchtarget",
            name="reservation_identifier",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plot_search_target",
                to="leasing.lease",
            ),
        ),
    ]
