# Generated by Django 3.2.18 on 2023-06-02 12:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("plotsearch", "0024_rename_intendeduse_areasearchintendeduse"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectReservationLink",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plot_search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plotsearch.plotsearch",
                    ),
                ),
            ],
        ),
    ]
