# Generated by Django 3.2.13 on 2023-08-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plotsearch", "0028_faq_translation_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areasearch",
            name="description_area",
            field=models.TextField(blank=True),
        ),
    ]
