# Generated by Django 3.2.13 on 2023-08-30 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0056_attach_usage_distribution_to_plan_unit"),
        ("plotsearch", "0029_alter_areasearch_description_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="areasearch",
            name="lease",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="area_searches",
                to="leasing.lease",
            ),
        ),
        migrations.AddField(
            model_name="targetstatus",
            name="lease",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_statuses",
                to="leasing.lease",
            ),
        ),
    ]
