# Generated by Django 3.2.13 on 2023-10-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plotsearch", "0030_auto_20231031_1149"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotsearchsubtype",
            name="require_opening_record",
            field=models.BooleanField(default=False),
        ),
    ]
