# Generated by Django 3.2.18 on 2024-02-08 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plotsearch", "0032_init_area_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="areasearchintendeduse",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="areasearch",
            name="intended_use",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="plotsearch.areasearchintendeduse",
            ),
        ),
    ]
