# Generated by Django 4.2.11 on 2024-04-09 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plotsearch", "0034_auto_20240320_1524"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotsearch",
            name="preparers",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Preparer",
            ),
        ),
    ]
