# Generated by Django 4.2.16 on 2024-12-17 08:11

from django.db import migrations


def replace_kuva_lessor(apps, schema_editor):
    """
    Replace the lessor field value for plotsearch_areasearch rows where
    KUVA was used.

    KUVA is not needed as a standalone service unit, because it is represented by
    its three sub-units NUP, LIPA, and UPA.

    NUP is used as a replacement because at the moment all the areasearch rows
    are for testing. Production environment table does not have any rows.
    """
    # Get the database connection
    connection = schema_editor.connection

    # Execute raw SQL to update the field
    with connection.cursor() as cursor:
        cursor.execute(
            """UPDATE plotsearch_areasearch SET lessor = %s WHERE lessor = %s""",
            ["NUP", "KUVA"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ("plotsearch", "0038_alter_favourite_user"),
    ]
    operations = [
        migrations.RunPython(replace_kuva_lessor),
    ]
