# Generated by Django 4.2.16 on 2025-01-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plotsearch", "0040_alter_areasearch_lessor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="areasearch",
            options={
                "verbose_name": "Area search",
                "verbose_name_plural": "Area searches",
            },
        ),
    ]
