# Generated by Django 4.2.16 on 2025-01-14 07:42

import django.core.files.storage
from django.db import migrations
import plotsearch.models.plot_search
import utils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("plotsearch", "0041_alter_areasearch_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areasearchattachment",
            name="attachment",
            field=utils.models.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/attachments/", location="attachments"
                ),
                upload_to=plotsearch.models.plot_search.get_area_search_attachment_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="meetingmemo",
            name="meeting_memo",
            field=utils.models.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/attachments/", location="attachments"
                ),
                upload_to=plotsearch.models.plot_search.get_meeting_memo_file_upload_to,
            ),
        ),
    ]
