# Generated by Django 4.2.20 on 2025-04-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plotsearch", "0042_private_filefield"),
    ]

    operations = [
        migrations.AddField(
            model_name="areasearchattachment",
            name="user_amr_list",
            field=models.CharField(
                blank=True,
                help_text="Authentication method reference",
                max_length=255,
                null=True,
                verbose_name="User amr",
            ),
        ),
    ]
