# Generated by Django 4.2.20 on 2025-04-24 12:24

import enumfields.fields
from django.db import migrations, models

import plotsearch.enums


class Migration(migrations.Migration):
    """Adds translations for model name, and two fields."""

    dependencies = [
        ("plotsearch", "0044_areasearch_settled_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="areasearchstatus",
            options={
                "verbose_name": "Area search status",
                "verbose_name_plural": "Area search statuses",
            },
        ),
        migrations.AlterField(
            model_name="areasearchstatus",
            name="decline_reason",
            field=enumfields.fields.EnumField(
                blank=True,
                enum=plotsearch.enums.DeclineReason,
                max_length=30,
                null=True,
                verbose_name="Decline reason",
            ),
        ),
        migrations.AlterField(
            model_name="areasearchstatus",
            name="preparer_note",
            field=models.TextField(blank=True, null=True, verbose_name="Preparer note"),
        ),
    ]
