# Generated by Django 4.2.19 on 2025-02-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("credit_integration", "0008_alter_creditdecision_original_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creditdecision",
            options={
                "permissions": [
                    ("send_creditdecision_inquiry", "Can send credit decision inquiry"),
                    ("send_sanctions_inquiry", "Can send sanctions inquiry"),
                ],
                "verbose_name": "Credit decision",
                "verbose_name_plural": "Credit decisions",
            },
        ),
    ]
