# Generated by Django 4.2.17 on 2025-01-28 13:04

from django.db import migrations, models
import utils.models.fields


class Migration(migrations.Migration):
    """
    Models to facilitate generic unit testing without relying on any specific
    concrete target model.
    """

    dependencies = [
        ("filescan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestGenericAttachmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_attachment",
                    utils.models.fields.PrivateFileField(
                        storage=utils.models.fields.PrivateFileSystemStorage(),
                        upload_to="",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestGenericSafeDeleteAttachmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "file_attachment",
                    utils.models.fields.PrivateFileField(
                        storage=utils.models.fields.PrivateFileSystemStorage(),
                        upload_to="",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
